// Site translation. Loaded in <head> on every page.
//
// - Visitors whose browser language is one of the 8 below get our own
//   translations (no third party involved): every English text node, plus
//   placeholder/aria-label/alt/title attributes, is swapped for its
//   translation as the page is built — and again whenever the app writes new
//   text later (a MutationObserver watches for it), so dynamic messages are
//   covered too, not just the static HTML.
// - Any other non-English language falls back to Google's page translator.
// - English browsers get the site exactly as written.
// - A small switcher (bottom-right) lets anyone override the choice.
//
// Pages opt in via <html data-i18n="...">:
//   "manual" — has entries in the dictionary below (home, early access, app)
//   "none"   — legal pages: never machine-translated, English only, with a note
//   (absent) — everything else: Google for any non-English language
//
// To add a string: add an entry to D with its 8 translations, in LANG order.
(function(){
  var LANGS = ["pt", "es", "de", "fr", "it", "nl", "pl", "ja"];
  var NAMES = { en: "English", pt: "Português", es: "Español", de: "Deutsch", fr: "Français", it: "Italiano", nl: "Nederlands", pl: "Polski", ja: "日本語" };
  var STORE = "printslice_lang";

  function norm(s){ return s.replace(/[‘’]/g, "'").replace(/[“”]/g, '"').replace(/\s+/g, " ").trim(); }

  function chosenLang(){ try { return localStorage.getItem(STORE); } catch (e) { return null; } }
  function browserTag(){ return ((navigator.languages && navigator.languages[0]) || navigator.language || "en").toLowerCase(); }
  var tag = chosenLang() || browserTag();
  var lang = tag.split("-")[0];
  var mode = document.documentElement.getAttribute("data-i18n") || "google";

  function googleCode(t){
    var b = t.split("-")[0];
    if (b === "zh") return /-(tw|hk|mo|hant)/.test(t) ? "zh-TW" : "zh-CN";
    return ({ he: "iw", jv: "jw", nb: "no", nn: "no", fil: "tl" })[b] || b;
  }

  function cookieDomains(){
    var h = location.hostname;
    return /^(localhost|\d+\.\d+\.\d+\.\d+)$/.test(h) ? [""] : ["", "; domain=" + h, "; domain=." + h.replace(/^www\./, "")];
  }
  function setGoogleCookie(code){ cookieDomains().forEach(function(d){ document.cookie = "googtrans=/en/" + code + "; path=/" + d; }); }
  function clearGoogleCookie(){ cookieDomains().forEach(function(d){ document.cookie = "googtrans=; Max-Age=0; path=/" + d; }); }

  /* ------------------------------------------------------------------ */
  /* Dictionary: English -> [pt, es, de, fr, it, nl, pl, ja]             */
  /* ------------------------------------------------------------------ */
  var D = {
    // header / nav / footer
    "Split big STL models into bed-sized, snap-fit pieces": ["Divida modelos STL grandes em peças do tamanho da sua mesa, com encaixe", "Divide modelos STL grandes en piezas del tamaño de tu cama, con encaje a presión", "Große STL-Modelle in druckbettgroße Teile mit Steckverbindungen aufteilen", "Découpez vos grands modèles STL en pièces à la taille de votre plateau, à emboîter", "Dividi i modelli STL grandi in pezzi a misura di piatto, a incastro", "Splits grote STL-modellen in stukken die op je printbed passen, met kliksluiting", "Dziel duże modele STL na części mieszczące się na stole, łączone na zatrzask", "大きなSTLモデルをベッドに収まるはめ込み式パーツに分割"],
    "Features": ["Recursos", "Funciones", "Funktionen", "Fonctionnalités", "Funzionalità", "Functies", "Funkcje", "機能"],
    "How It Works": ["Como funciona", "Cómo funciona", "So funktioniert's", "Comment ça marche", "Come funziona", "Hoe het werkt", "Jak to działa", "使い方"],
    "Pricing": ["Preços", "Precios", "Preise", "Tarifs", "Prezzi", "Prijzen", "Cennik", "料金"],
    "Free Trial": ["Teste grátis", "Prueba gratis", "Kostenlos testen", "Essai gratuit", "Prova gratuita", "Gratis proberen", "Darmowy okres próbny", "無料トライアル"],
    "FAQ": ["Dúvidas", "Preguntas", "FAQ", "FAQ", "FAQ", "FAQ", "FAQ", "よくある質問"],
    "Community": ["Comunidade", "Comunidad", "Community", "Communauté", "Community", "Community", "Społeczność", "コミュニティ"],
    "Log In": ["Entrar", "Iniciar sesión", "Anmelden", "Connexion", "Accedi", "Inloggen", "Zaloguj się", "ログイン"],
    "Start Slicing": ["Começar", "Empezar", "Loslegen", "Commencer", "Inizia", "Beginnen", "Zacznij", "はじめる"],
    "Help": ["Ajuda", "Ayuda", "Hilfe", "Aide", "Aiuto", "Help", "Pomoc", "ヘルプ"],
    "Product": ["Produto", "Producto", "Produkt", "Produit", "Prodotto", "Product", "Produkt", "製品"],
    "Company": ["Empresa", "Empresa", "Unternehmen", "Entreprise", "Azienda", "Bedrijf", "Firma", "会社"],
    "Contact": ["Contato", "Contacto", "Kontakt", "Contact", "Contatti", "Contact", "Kontakt", "お問い合わせ"],
    "Legal": ["Jurídico", "Legal", "Rechtliches", "Mentions légales", "Note legali", "Juridisch", "Informacje prawne", "法的情報"],
    "Terms": ["Termos", "Términos", "AGB", "Conditions", "Termini", "Voorwaarden", "Regulamin", "利用規約"],
    "Privacy": ["Privacidade", "Privacidad", "Datenschutz", "Confidentialité", "Privacy", "Privacy", "Prywatność", "プライバシー"],
    "PrintSlice logo": ["Logotipo do PrintSlice", "Logotipo de PrintSlice", "PrintSlice-Logo", "Logo PrintSlice", "Logo di PrintSlice", "PrintSlice-logo", "Logo PrintSlice", "PrintSliceロゴ"],
    "Split oversized models into printable, precisely connected pieces.": ["Divida modelos grandes demais em peças imprimíveis e com encaixe preciso.", "Divide modelos demasiado grandes en piezas imprimibles y unidas con precisión.", "Zu große Modelle in druckbare, präzise verbundene Teile aufteilen.", "Découpez les modèles trop grands en pièces imprimables, assemblées avec précision.", "Dividi i modelli troppo grandi in pezzi stampabili e collegati con precisione.", "Splits te grote modellen in printbare, nauwkeurig verbonden stukken.", "Dziel zbyt duże modele na części do druku, precyzyjnie łączone.", "大きすぎるモデルを、印刷できて精密につながるパーツに分割。"],
    "PrintSlice — Split big STL models into bed-sized, snap-fit pieces": ["PrintSlice — Divida modelos STL grandes em peças do tamanho da mesa", "PrintSlice — Divide modelos STL grandes en piezas del tamaño de tu cama", "PrintSlice — Große STL-Modelle in druckbettgroße Teile aufteilen", "PrintSlice — Découpez vos grands STL à la taille de votre plateau", "PrintSlice — Dividi gli STL grandi in pezzi a misura di piatto", "PrintSlice — Splits grote STL-modellen in stukken die op je bed passen", "PrintSlice — Dziel duże modele STL na części na Twój stół", "PrintSlice — 大きなSTLをベッドサイズのパーツに分割"],

    // homepage
    "Fig. 01 — Bed-Size Splitting": ["Fig. 01 — Divisão no tamanho da mesa", "Fig. 01 — División al tamaño de la cama", "Abb. 01 — Aufteilung nach Druckbettgröße", "Fig. 01 — Découpe à la taille du plateau", "Fig. 01 — Divisione a misura di piatto", "Fig. 01 — Opsplitsen op bedformaat", "Rys. 01 — Podział na wymiar stołu", "図01 — ベッドサイズ分割"],
    "Big prints.": ["Impressões grandes.", "Impresiones grandes.", "Große Drucke.", "Grandes impressions.", "Stampe grandi.", "Grote prints.", "Duże wydruki.", "大きなプリント。"],
    "Small beds.": ["Mesas pequenas.", "Camas pequeñas.", "Kleine Druckbetten.", "Petits plateaux.", "Piatti piccoli.", "Kleine printbedden.", "Małe stoły.", "小さなベッド。"],
    "Solved.": ["Resolvido.", "Resuelto.", "Gelöst.", "Réglé.", "Risolto.", "Opgelost.", "Rozwiązane.", "解決。"],
    "PrintSlice cuts oversized STL files into pieces your printer can actually hold, then engineers the connectors that pull them back together after printing.": ["O PrintSlice corta arquivos STL grandes demais em peças que sua impressora consegue imprimir e cria os conectores que as unem de novo depois da impressão.", "PrintSlice corta archivos STL demasiado grandes en piezas que tu impresora sí puede imprimir y diseña los conectores que las vuelven a unir después de imprimir.", "PrintSlice zerlegt zu große STL-Dateien in Teile, die dein Drucker wirklich schafft, und konstruiert die Verbinder, die sie nach dem Druck wieder zusammenhalten.", "PrintSlice découpe les fichiers STL trop grands en pièces que votre imprimante peut vraiment imprimer, puis conçoit les connecteurs qui les réassemblent après l'impression.", "PrintSlice taglia i file STL troppo grandi in pezzi che la tua stampante può davvero stampare, poi progetta i connettori che li riuniscono dopo la stampa.", "PrintSlice snijdt te grote STL-bestanden in stukken die je printer echt aankan, en ontwerpt de verbindingen die ze na het printen weer samenvoegen.", "PrintSlice tnie zbyt duże pliki STL na części, które Twoja drukarka naprawdę zmieści, a potem projektuje łączniki, które po wydruku złączą je z powrotem.", "PrintSliceは大きすぎるSTLファイルをプリンターで印刷できるパーツに分割し、印刷後に再びつなぎ合わせるコネクターを設計します。"],
    "Start Free Trial": ["Começar teste grátis", "Empezar prueba gratis", "Kostenlos testen", "Commencer l'essai gratuit", "Inizia la prova gratuita", "Start gratis proefperiode", "Zacznij za darmo", "無料で試す"],
    "See How It Works": ["Veja como funciona", "Mira cómo funciona", "So funktioniert's", "Voir comment ça marche", "Guarda come funziona", "Bekijk hoe het werkt", "Zobacz, jak to działa", "使い方を見る"],
    "TRY IT FREE, NO CARD · 7-DAY FREE TRIAL TO DOWNLOAD · CANCEL ANYTIME": ["TESTE GRÁTIS, SEM CARTÃO · 7 DIAS GRÁTIS PARA BAIXAR · CANCELE QUANDO QUISER", "PRUÉBALO GRATIS, SIN TARJETA · 7 DÍAS GRATIS PARA DESCARGAR · CANCELA CUANDO QUIERAS", "KOSTENLOS TESTEN, OHNE KARTE · 7 TAGE GRATIS ZUM HERUNTERLADEN · JEDERZEIT KÜNDBAR", "ESSAI GRATUIT, SANS CARTE · 7 JOURS GRATUITS POUR TÉLÉCHARGER · ANNULABLE À TOUT MOMENT", "PROVALO GRATIS, SENZA CARTA · 7 GIORNI GRATIS PER SCARICARE · DISDICI QUANDO VUOI", "GRATIS PROBEREN, ZONDER KAART · 7 DAGEN GRATIS OM TE DOWNLOADEN · ALTIJD OPZEGBAAR", "WYPRÓBUJ ZA DARMO, BEZ KARTY · 7 DNI ZA DARMO NA POBIERANIE · ANULUJ W KAŻDEJ CHWILI", "カード不要で無料お試し · ダウンロードは7日間無料トライアル · いつでも解約可能"],
    "Preview": ["Prévia", "Vista previa", "Vorschau", "Aperçu", "Anteprima", "Voorbeeld", "Podgląd", "プレビュー"],
    "Open the file, watch it divide": ["Abra o arquivo e veja ele se dividir", "Abre el archivo y mira cómo se divide", "Datei öffnen, zusehen, wie sie sich teilt", "Ouvrez le fichier, regardez-le se découper", "Apri il file e guardalo dividersi", "Open het bestand en zie het opsplitsen", "Otwórz plik i patrz, jak się dzieli", "ファイルを開けば、分割される様子が見えます"],
    "Every cut, measurement, and connector placement happens live in the viewport — no export, no guesswork, no waiting on a server.": ["Cada corte, medida e conector acontece ao vivo na tela — sem exportar, sem adivinhar, sem esperar um servidor.", "Cada corte, medida y conector se ve en directo en el visor: sin exportar, sin adivinar, sin esperar a un servidor.", "Jeder Schnitt, jedes Maß und jeder Verbinder passiert live in der Ansicht — kein Export, kein Raten, kein Warten auf einen Server.", "Chaque découpe, mesure et connecteur s'affiche en direct dans la vue — pas d'export, pas d'approximation, pas d'attente serveur.", "Ogni taglio, misura e connettore avviene in tempo reale nella vista: niente esportazioni, niente tentativi, niente attese del server.", "Elke snede, maat en verbinding zie je live in het venster — geen export, geen gokwerk, niet wachten op een server.", "Każde cięcie, wymiar i łącznik widać na żywo w podglądzie — bez eksportu, zgadywania i czekania na serwer.", "カット、寸法、コネクターの配置はすべてビューポート上でリアルタイムに行われます。書き出しも勘も、サーバー待ちも不要です。"],
    "From one file to finished parts": ["De um arquivo a peças prontas", "De un archivo a piezas terminadas", "Von einer Datei zu fertigen Teilen", "D'un fichier à des pièces finies", "Da un file a pezzi finiti", "Van één bestand naar kant-en-klare onderdelen", "Od jednego pliku do gotowych części", "1つのファイルから完成パーツまで"],
    "Drop it in": ["Solte o arquivo", "Suéltalo", "Reinziehen", "Déposez-le", "Trascinalo", "Sleep het erin", "Upuść plik", "ドロップする"],
    "Any STL, any size — dragged straight into the browser and read on the spot.": ["Qualquer STL, de qualquer tamanho — arraste para o navegador e ele é lido na hora.", "Cualquier STL, de cualquier tamaño: arrástralo al navegador y se lee al instante.", "Jede STL, jede Größe — direkt in den Browser ziehen, sofort eingelesen.", "N'importe quel STL, de n'importe quelle taille — glissé dans le navigateur et lu sur-le-champ.", "Qualsiasi STL, di qualsiasi dimensione: trascinalo nel browser e viene letto all'istante.", "Elke STL, elk formaat — sleep hem in de browser en hij wordt meteen ingelezen.", "Dowolny STL, dowolnego rozmiaru — przeciągnij do przeglądarki, a zostanie od razu wczytany.", "どんなサイズのSTLでも、ブラウザにドラッグするだけですぐに読み込まれます。"],
    "Draw the lines": ["Defina os cortes", "Marca los cortes", "Schnitte festlegen", "Tracez les coupes", "Traccia i tagli", "Bepaal de snedes", "Wyznacz cięcia", "カット位置を決める"],
    "Tell PrintSlice your bed dimensions — it finds the cuts that make everything fit.": ["Informe o tamanho da sua mesa — o PrintSlice encontra os cortes para tudo caber.", "Indica a PrintSlice las medidas de tu cama y encontrará los cortes para que todo quepa.", "Gib PrintSlice die Maße deines Druckbetts an — es findet die Schnitte, damit alles passt.", "Indiquez à PrintSlice les dimensions de votre plateau — il trouve les découpes pour que tout rentre.", "Indica a PrintSlice le misure del piatto: troverà i tagli perché tutto ci stia.", "Geef PrintSlice de afmetingen van je printbed — het vindt de snedes zodat alles past.", "Podaj PrintSlice wymiary stołu — znajdzie cięcia, dzięki którym wszystko się zmieści.", "ベッドの寸法を入力すれば、すべてが収まるカット位置をPrintSliceが見つけます。"],
    "Print & lock together": ["Imprima e encaixe", "Imprime y encaja", "Drucken & zusammenstecken", "Imprimez et emboîtez", "Stampa e incastra", "Printen en in elkaar klikken", "Drukuj i składaj", "印刷してはめ込む"],
    "Matching connectors print right into the seams, so assembly is just pressing pieces home.": ["Os conectores saem impressos nas emendas, então montar é só encaixar as peças.", "Los conectores se imprimen en las uniones, así que montar es solo encajar las piezas.", "Passende Verbinder werden direkt in die Nahtstellen gedruckt — zum Zusammenbau steckst du die Teile einfach ineinander.", "Les connecteurs sont imprimés directement dans les jointures : l'assemblage consiste simplement à emboîter les pièces.", "I connettori vengono stampati direttamente nelle giunture: per montare basta incastrare i pezzi.", "Bijpassende verbindingen worden in de naden meegeprint, dus monteren is gewoon de stukken in elkaar drukken.", "Pasujące łączniki drukują się od razu na łączeniach, więc składanie to tylko wciśnięcie części na miejsce.", "対応するコネクターが継ぎ目に一緒に印刷されるので、組み立てはパーツを押し込むだけです。"],
    "Fig. 04 — Seam Detail": ["Fig. 04 — Detalhe da emenda", "Fig. 04 — Detalle de la unión", "Abb. 04 — Nahtdetail", "Fig. 04 — Détail de la jointure", "Fig. 04 — Dettaglio della giuntura", "Fig. 04 — Detail van de naad", "Rys. 04 — Szczegół łączenia", "図04 — 継ぎ目の詳細"],
    "Connectors": ["Conectores", "Conectores", "Verbinder", "Connecteurs", "Connettori", "Verbindingen", "Łączniki", "コネクター"],
    "A joint engineered, not eyeballed": ["Uma junta projetada, não no olho", "Una unión diseñada, no a ojo", "Eine konstruierte Verbindung, nicht nach Augenmaß", "Un assemblage conçu, pas fait à l'œil", "Un incastro progettato, non a occhio", "Een ontworpen verbinding, niet op het oog", "Złącze zaprojektowane, a nie na oko", "目分量ではなく設計されたジョイント"],
    "Each seam gets a tab and a socket cut from the same geometry, with clearance dialed in automatically — no filing, no glue, no guesswork.": ["Cada emenda recebe um encaixe macho e fêmea cortados da mesma geometria, com folga ajustada automaticamente — sem lixar, sem cola, sem adivinhação.", "Cada unión recibe una pestaña y un hueco cortados de la misma geometría, con la holgura ajustada automáticamente: sin limar, sin pegamento, sin adivinar.", "Jede Naht bekommt Zapfen und Aufnahme aus derselben Geometrie, mit automatisch eingestelltem Spiel — kein Feilen, kein Kleber, kein Raten.", "Chaque jointure reçoit un tenon et une mortaise taillés dans la même géométrie, avec un jeu réglé automatiquement — sans limer, sans colle, sans approximation.", "Ogni giuntura riceve un maschio e una femmina ricavati dalla stessa geometria, con gioco regolato automaticamente: niente lima, niente colla, niente tentativi.", "Elke naad krijgt een lip en een sleuf uit dezelfde geometrie, met automatisch ingestelde speling — geen vijlen, geen lijm, geen gokwerk.", "Każde łączenie dostaje wypust i gniazdo wycięte z tej samej geometrii, z automatycznie dobranym luzem — bez piłowania, kleju i zgadywania.", "各継ぎ目には同じ形状から切り出したタブとソケットが付き、クリアランスも自動調整されます。やすりも接着剤も勘も不要です。"],
    "Keyed, pinned, or dovetailed — pick per seam": ["Chaveta, pino ou rabo de andorinha — escolha por emenda", "Chaveta, pasador o cola de milano: elige en cada unión", "Passfeder, Stift oder Schwalbenschwanz — pro Naht wählbar", "À clavette, à goupille ou en queue d'aronde — au choix par jointure", "A chiavetta, a perno o a coda di rondine: scegli per ogni giuntura", "Spie, pen of zwaluwstaart — kies per naad", "Klin, kołek lub jaskółczy ogon — wybór dla każdego łączenia", "キー、ピン、アリ継ぎから継ぎ目ごとに選択"],
    "Clearance tuned to your printer's tolerance": ["Folga ajustada à tolerância da sua impressora", "Holgura ajustada a la tolerancia de tu impresora", "Spiel passend zur Toleranz deines Druckers", "Jeu adapté à la tolérance de votre imprimante", "Gioco adattato alla tolleranza della tua stampante", "Speling afgestemd op de tolerantie van je printer", "Luz dopasowany do tolerancji Twojej drukarki", "プリンターの公差に合わせたクリアランス"],
    "Solved from the mesh itself, not a template": ["Calculado a partir da própria malha, não de um modelo pronto", "Calculado a partir de la propia malla, no de una plantilla", "Aus dem Mesh selbst berechnet, nicht aus einer Vorlage", "Calculé à partir du maillage lui-même, pas d'un gabarit", "Calcolato dalla mesh stessa, non da un modello", "Berekend uit het model zelf, niet uit een sjabloon", "Wyliczone z samej siatki, a nie z szablonu", "テンプレートではなくメッシュ自体から算出"],
    "What's actually doing the work": ["O que faz o trabalho de verdade", "Lo que realmente hace el trabajo", "Was hier wirklich arbeitet", "Ce qui fait vraiment le travail", "Cosa fa davvero il lavoro", "Wat het werk echt doet", "Co tak naprawdę wykonuje pracę", "実際に何をしているのか"],
    "Reads Any Mesh": ["Lê qualquer malha", "Lee cualquier malla", "Liest jedes Mesh", "Lit n'importe quel maillage", "Legge qualsiasi mesh", "Leest elk model", "Czyta każdą siatkę", "どんなメッシュも読み込み"],
    "Binary or ASCII STL, simple or dense — parsed locally the moment you drop it in.": ["STL binário ou ASCII, simples ou denso — lido no seu computador assim que você solta o arquivo.", "STL binario o ASCII, sencillo o denso: se procesa en tu equipo en cuanto lo sueltas.", "Binäre oder ASCII-STL, einfach oder detailreich — lokal eingelesen, sobald du sie ablegst.", "STL binaire ou ASCII, simple ou dense — analysé localement dès que vous le déposez.", "STL binario o ASCII, semplice o denso: elaborato in locale appena lo trascini.", "Binaire of ASCII-STL, eenvoudig of complex — lokaal ingelezen zodra je hem neerzet.", "STL binarny lub ASCII, prosty lub gęsty — przetwarzany lokalnie, gdy tylko go upuścisz.", "バイナリでもASCIIでも、シンプルでも高密度でも、ドロップした瞬間にローカルで解析します。"],
    "Knows Your Bed": ["Conhece sua mesa", "Conoce tu cama", "Kennt dein Druckbett", "Connaît votre plateau", "Conosce il tuo piatto", "Kent je printbed", "Zna Twój stół", "ベッドを把握"],
    "Set your build volume once — every cut respects it automatically.": ["Defina o volume de impressão uma vez — todo corte respeita isso automaticamente.", "Configura tu volumen de impresión una vez y cada corte lo respetará automáticamente.", "Bauraum einmal festlegen — jeder Schnitt hält sich automatisch daran.", "Définissez votre volume d'impression une fois — chaque découpe le respecte automatiquement.", "Imposta il volume di stampa una volta: ogni taglio lo rispetta automaticamente.", "Stel je bouwvolume één keer in — elke snede houdt er automatisch rekening mee.", "Ustaw obszar roboczy raz — każde cięcie automatycznie się do niego dostosuje.", "造形サイズを一度設定すれば、すべてのカットが自動的にそれに従います。"],
    "Cuts Real Joints": ["Cria juntas reais", "Crea uniones reales", "Schneidet echte Verbindungen", "Taille de vrais assemblages", "Crea incastri veri", "Maakt echte verbindingen", "Wycina prawdziwe złącza", "本物のジョイントを作成"],
    "Connectors come from the model's own geometry, not a generic bolt-on shape.": ["Os conectores vêm da própria geometria do modelo, não de uma peça genérica colada.", "Los conectores salen de la propia geometría del modelo, no de una pieza genérica añadida.", "Verbinder entstehen aus der Geometrie des Modells, nicht aus einer generischen Aufsteckform.", "Les connecteurs viennent de la géométrie même du modèle, pas d'une forme générique ajoutée.", "I connettori nascono dalla geometria del modello, non da una forma generica aggiunta.", "Verbindingen komen uit de geometrie van het model zelf, niet uit een standaardvorm.", "Łączniki powstają z geometrii samego modelu, a nie z ogólnego, doklejanego kształtu.", "コネクターは汎用の後付け形状ではなく、モデル自体の形状から作られます。"],
    "Nothing Leaves Your Machine": ["Nada sai do seu computador", "Nada sale de tu equipo", "Nichts verlässt deinen Rechner", "Rien ne quitte votre ordinateur", "Niente lascia il tuo computer", "Niets verlaat je computer", "Nic nie opuszcza Twojego komputera", "データは端末の外に出ません"],
    "The split, the joints, the preview — computed client-side, always.": ["A divisão, as juntas, a prévia — tudo calculado no seu navegador, sempre.", "La división, las uniones, la vista previa: todo se calcula en tu navegador, siempre.", "Aufteilung, Verbinder, Vorschau — immer direkt im Browser berechnet.", "La découpe, les assemblages, l'aperçu — toujours calculés dans votre navigateur.", "Divisione, incastri, anteprima: tutto calcolato nel tuo browser, sempre.", "Het opsplitsen, de verbindingen, het voorbeeld — altijd in je browser berekend.", "Podział, złącza, podgląd — zawsze liczone w Twojej przeglądarce.", "分割もジョイントもプレビューも、常にブラウザ内で計算されます。"],
    "Built For Big Meshes": ["Feito para malhas grandes", "Hecho para mallas grandes", "Gebaut für große Meshes", "Conçu pour les gros maillages", "Pensato per mesh grandi", "Gemaakt voor grote modellen", "Stworzony dla dużych siatek", "大きなメッシュ向けに設計"],
    "Kept fast even as triangle counts climb.": ["Continua rápido mesmo com muitos triângulos.", "Sigue siendo rápido aunque aumenten los triángulos.", "Bleibt schnell, auch bei vielen Dreiecken.", "Reste rapide même quand le nombre de triangles grimpe.", "Resta veloce anche con molti triangoli.", "Blijft snel, ook bij veel driehoeken.", "Działa szybko nawet przy dużej liczbie trójkątów.", "三角形の数が増えても高速です。"],
    "Snaps Together Fast": ["Encaixa rápido", "Encaja rápido", "Schnell zusammengesteckt", "S'emboîte en un clin d'œil", "Si incastra in un attimo", "Klikt snel in elkaar", "Szybko się składa", "すぐにはまる"],
    "Parts line up on the first try — no post-processing required.": ["As peças se alinham de primeira — sem pós-processamento.", "Las piezas encajan a la primera, sin posprocesado.", "Teile passen auf Anhieb — keine Nachbearbeitung nötig.", "Les pièces s'alignent du premier coup — sans post-traitement.", "I pezzi si allineano al primo colpo, senza post-lavorazione.", "Onderdelen passen meteen — geen nabewerking nodig.", "Części pasują za pierwszym razem — bez obróbki.", "パーツは一度でぴったり揃い、後処理は不要です。"],
    "Bigger than the bed, until now": ["Maior que a mesa — até agora", "Más grande que la cama, hasta ahora", "Größer als das Druckbett — bis jetzt", "Plus grand que le plateau, jusqu'à maintenant", "Più grande del piatto, fino a oggi", "Groter dan het printbed — tot nu", "Większe niż stół — aż do teraz", "ベッドより大きい — これまでは"],
    "Won't Fit": ["Não cabe", "No cabe", "Passt nicht", "Ne rentre pas", "Non ci sta", "Past niet", "Nie mieści się", "収まらない"],
    "Fits, In Four": ["Cabe, em quatro", "Cabe, en cuatro", "Passt, in vier Teilen", "Rentre, en quatre", "Ci sta, in quattro", "Past, in vier", "Mieści się, w czterech", "4分割で収まる"],
    "One number, no fine print": ["Um preço, sem letras miúdas", "Un precio, sin letra pequeña", "Ein Preis, kein Kleingedrucktes", "Un seul prix, sans petites lignes", "Un solo prezzo, niente clausole nascoste", "Eén prijs, geen kleine lettertjes", "Jedna cena, bez drobnego druku", "料金はひとつ、細かい条件なし"],
    "Every feature, every connector type, no upsells.": ["Todos os recursos, todos os tipos de conector, sem extras pagos.", "Todas las funciones, todos los conectores, sin extras de pago.", "Alle Funktionen, alle Verbindertypen, keine Zusatzkosten.", "Toutes les fonctionnalités, tous les connecteurs, sans supplément.", "Tutte le funzioni, tutti i connettori, nessun extra a pagamento.", "Alle functies, alle verbindingstypes, geen extra's.", "Wszystkie funkcje, wszystkie łączniki, bez dopłat.", "全機能・全コネクター込み、追加料金なし。"],
    "/MO": ["/MÊS", "/MES", "/MONAT", "/MOIS", "/MESE", "/MAAND", "/MIES.", "/月"],
    "Unlimited STL splits": ["Divisões de STL ilimitadas", "Divisiones de STL ilimitadas", "Unbegrenzt STL-Dateien aufteilen", "Découpes STL illimitées", "Divisioni STL illimitate", "Onbeperkt STL's opsplitsen", "Nielimitowany podział STL", "STL分割し放題"],
    "Real solid-geometry connectors": ["Conectores de geometria sólida real", "Conectores de geometría sólida real", "Verbinder aus echter Volumengeometrie", "Connecteurs en vraie géométrie solide", "Connettori in vera geometria solida", "Verbindingen van echte solide geometrie", "Łączniki z prawdziwej bryły", "本物のソリッド形状コネクター"],
    "Rectangular key, pin, and dovetail joints": ["Juntas de chaveta, pino e rabo de andorinha", "Uniones de chaveta, pasador y cola de milano", "Passfeder-, Stift- und Schwalbenschwanzverbindungen", "Assemblages à clavette, goupille et queue d'aronde", "Incastri a chiavetta, perno e coda di rondine", "Spie-, pen- en zwaluwstaartverbindingen", "Złącza klinowe, kołkowe i na jaskółczy ogon", "角キー、ピン、アリ継ぎジョイント"],
    "Cancel anytime": ["Cancele quando quiser", "Cancela cuando quieras", "Jederzeit kündbar", "Annulable à tout moment", "Disdici quando vuoi", "Altijd opzegbaar", "Anuluj w każdej chwili", "いつでも解約可能"],
    "Want to try before you subscribe?": ["Quer testar antes de assinar?", "¿Quieres probar antes de suscribirte?", "Erst ausprobieren?", "Envie d'essayer avant de vous abonner ?", "Vuoi provare prima di abbonarti?", "Eerst proberen voordat je abonneert?", "Chcesz wypróbować przed subskrypcją?", "登録前に試してみませんか？"],
    "Start a free 7-day trial": ["Comece um teste grátis de 7 dias", "Empieza una prueba gratis de 7 días", "7 Tage kostenlos testen", "Commencez un essai gratuit de 7 jours", "Inizia una prova gratuita di 7 giorni", "Start een gratis proefperiode van 7 dagen", "Zacznij 7-dniowy okres próbny", "7日間の無料トライアルを開始"],
    "Before you ask": ["Antes que você pergunte", "Antes de que preguntes", "Bevor du fragst", "Avant que vous demandiez", "Prima che tu lo chieda", "Voordat je het vraagt", "Zanim zapytasz", "よくある質問"],
    "What is PrintSlice?": ["O que é o PrintSlice?", "¿Qué es PrintSlice?", "Was ist PrintSlice?", "Qu'est-ce que PrintSlice ?", "Cos'è PrintSlice?", "Wat is PrintSlice?", "Czym jest PrintSlice?", "PrintSliceとは？"],
    "A browser-based tool that splits oversized STL models into bed-sized pieces and generates matching connectors so they assemble back into the original shape.": ["Uma ferramenta no navegador que divide modelos STL grandes demais em peças do tamanho da mesa e gera conectores para montá-las de volta no formato original.", "Una herramienta en el navegador que divide modelos STL demasiado grandes en piezas del tamaño de la cama y genera conectores para volver a montarlas en su forma original.", "Ein Browser-Tool, das zu große STL-Modelle in druckbettgroße Teile zerlegt und passende Verbinder erzeugt, damit sie sich wieder zur ursprünglichen Form zusammensetzen lassen.", "Un outil dans le navigateur qui découpe les modèles STL trop grands en pièces à la taille du plateau et génère des connecteurs pour les réassembler dans leur forme d'origine.", "Uno strumento nel browser che divide i modelli STL troppo grandi in pezzi a misura di piatto e genera connettori per riassemblarli nella forma originale.", "Een browsertool die te grote STL-modellen opsplitst in stukken die op je printbed passen en bijpassende verbindingen maakt, zodat ze weer in de oorspronkelijke vorm in elkaar passen.", "Narzędzie w przeglądarce, które dzieli zbyt duże modele STL na części mieszczące się na stole i tworzy pasujące łączniki, by złożyć je z powrotem w oryginalny kształt.", "大きすぎるSTLモデルをベッドに収まるパーツに分割し、元の形に組み立て直せるコネクターを生成するブラウザツールです。"],
    "What file types are supported?": ["Quais tipos de arquivo são aceitos?", "¿Qué tipos de archivo admite?", "Welche Dateitypen werden unterstützt?", "Quels types de fichiers sont pris en charge ?", "Quali tipi di file sono supportati?", "Welke bestandstypen worden ondersteund?", "Jakie typy plików są obsługiwane?", "対応ファイル形式は？"],
    "STL files, both binary and ASCII, for input — and binary STL for the split output pieces, the standard format every slicer accepts.": ["Arquivos STL, binários e ASCII, na entrada — e STL binário nas peças geradas, o formato padrão que todo fatiador aceita.", "Archivos STL, binarios y ASCII, de entrada, y STL binario para las piezas resultantes, el formato estándar que acepta cualquier laminador.", "STL-Dateien, binär und ASCII, als Eingabe — und binäre STL für die aufgeteilten Teile, das Standardformat, das jeder Slicer versteht.", "Des fichiers STL, binaires et ASCII, en entrée — et du STL binaire pour les pièces découpées, le format standard accepté par tous les trancheurs.", "File STL, binari e ASCII, in ingresso, e STL binario per i pezzi divisi, il formato standard accettato da ogni slicer.", "STL-bestanden, binair en ASCII, als invoer — en binaire STL voor de opgesplitste stukken, het standaardformaat dat elke slicer accepteert.", "Na wejściu pliki STL, binarne i ASCII, a na wyjściu binarne STL — standardowy format, który przyjmuje każdy slicer.", "入力はバイナリ・ASCII両方のSTL、分割後のパーツはどのスライサーでも使える標準のバイナリSTLで出力します。"],
    "How does automatic splitting work?": ["Como funciona a divisão automática?", "¿Cómo funciona la división automática?", "Wie funktioniert das automatische Aufteilen?", "Comment fonctionne la découpe automatique ?", "Come funziona la divisione automatica?", "Hoe werkt automatisch opsplitsen?", "Jak działa automatyczny podział?", "自動分割の仕組みは？"],
    "You set your printer's bed size and a safety margin; PrintSlice computes watertight cuts through the model so every resulting piece fits within that volume.": ["Você define o tamanho da mesa e uma margem de segurança; o PrintSlice calcula cortes fechados no modelo para que cada peça caiba nesse volume.", "Tú indicas el tamaño de la cama y un margen de seguridad; PrintSlice calcula cortes cerrados en el modelo para que cada pieza quepa en ese volumen.", "Du gibst Druckbettgröße und Sicherheitsabstand an; PrintSlice berechnet wasserdichte Schnitte durch das Modell, sodass jedes Teil in diesen Bauraum passt.", "Vous indiquez la taille du plateau et une marge de sécurité ; PrintSlice calcule des découpes étanches dans le modèle pour que chaque pièce tienne dans ce volume.", "Imposti la dimensione del piatto e un margine di sicurezza; PrintSlice calcola tagli chiusi nel modello perché ogni pezzo stia in quel volume.", "Jij stelt je bedformaat en een veiligheidsmarge in; PrintSlice berekent waterdichte snedes door het model, zodat elk stuk binnen dat volume past.", "Ustawiasz wymiar stołu i margines bezpieczeństwa; PrintSlice wylicza szczelne cięcia przez model, by każda część zmieściła się w tym obszarze.", "ベッドサイズと余白を設定すると、PrintSliceがモデルを密閉されたまま分割し、すべてのパーツがその範囲に収まるようにします。"],
    "How do the connectors work?": ["Como funcionam os conectores?", "¿Cómo funcionan los conectores?", "Wie funktionieren die Verbinder?", "Comment fonctionnent les connecteurs ?", "Come funzionano i connettori?", "Hoe werken de verbindingen?", "Jak działają łączniki?", "コネクターの仕組みは？"],
    "Every connector pair — the tab and its matching socket — is generated from one shared definition using real solid geometry, with a small configurable clearance built in.": ["Cada par de conectores — o encaixe macho e o fêmea — é gerado a partir de uma única definição com geometria sólida real, com uma pequena folga ajustável.", "Cada par de conectores —la pestaña y su hueco— se genera a partir de una sola definición con geometría sólida real, con una pequeña holgura configurable.", "Jedes Verbinderpaar — Zapfen und passende Aufnahme — entsteht aus einer gemeinsamen Definition mit echter Volumengeometrie und einem kleinen einstellbaren Spiel.", "Chaque paire de connecteurs — le tenon et sa mortaise — est générée à partir d'une même définition en géométrie solide réelle, avec un petit jeu réglable intégré.", "Ogni coppia di connettori, maschio e femmina, nasce da un'unica definizione in vera geometria solida, con un piccolo gioco regolabile già incluso.", "Elk paar verbindingen — de lip en de bijpassende sleuf — wordt gemaakt uit één gedeelde definitie met echte solide geometrie, met een kleine instelbare speling.", "Każda para łączników — wypust i pasujące gniazdo — powstaje z jednej wspólnej definicji z prawdziwej bryły, z niewielkim, regulowanym luzem.", "各コネクターのペア（タブと対応するソケット）は本物のソリッド形状による共通定義から生成され、調整可能な小さなクリアランスが組み込まれています。"],
    "Does PrintSlice work with any 3D printer?": ["O PrintSlice funciona com qualquer impressora 3D?", "¿PrintSlice funciona con cualquier impresora 3D?", "Funktioniert PrintSlice mit jedem 3D-Drucker?", "PrintSlice fonctionne-t-il avec toutes les imprimantes 3D ?", "PrintSlice funziona con qualsiasi stampante 3D?", "Werkt PrintSlice met elke 3D-printer?", "Czy PrintSlice działa z każdą drukarką 3D?", "どんな3Dプリンターでも使えますか？"],
    "Yes — the exported pieces are standard STL files, compatible with any slicer or printer you already use.": ["Sim — as peças exportadas são arquivos STL padrão, compatíveis com qualquer fatiador ou impressora que você já usa.", "Sí: las piezas exportadas son archivos STL estándar, compatibles con cualquier laminador o impresora que ya uses.", "Ja — die exportierten Teile sind normale STL-Dateien, kompatibel mit jedem Slicer und Drucker, den du schon nutzt.", "Oui — les pièces exportées sont des fichiers STL standard, compatibles avec n'importe quel trancheur ou imprimante que vous utilisez déjà.", "Sì: i pezzi esportati sono file STL standard, compatibili con qualsiasi slicer o stampante che usi già.", "Ja — de geëxporteerde stukken zijn standaard STL-bestanden, geschikt voor elke slicer of printer die je al gebruikt.", "Tak — wyeksportowane części to standardowe pliki STL, zgodne z każdym slicerem i drukarką, których już używasz.", "はい。書き出したパーツは標準のSTLファイルなので、お使いのスライサーやプリンターで使えます。"],
    "Do I need to install anything?": ["Preciso instalar alguma coisa?", "¿Tengo que instalar algo?", "Muss ich etwas installieren?", "Faut-il installer quelque chose ?", "Devo installare qualcosa?", "Moet ik iets installeren?", "Czy muszę coś instalować?", "インストールは必要ですか？"],
    "No. Splitting, connector generation, and the 3D preview all run in your browser — nothing to install, and your model never leaves your computer.": ["Não. A divisão, os conectores e a prévia 3D rodam no seu navegador — nada para instalar, e seu modelo nunca sai do seu computador.", "No. La división, los conectores y la vista previa 3D funcionan en tu navegador: no hay nada que instalar y tu modelo nunca sale de tu equipo.", "Nein. Aufteilen, Verbinder und 3D-Vorschau laufen im Browser — nichts zu installieren, und dein Modell verlässt nie deinen Rechner.", "Non. La découpe, les connecteurs et l'aperçu 3D fonctionnent dans votre navigateur — rien à installer, et votre modèle ne quitte jamais votre ordinateur.", "No. Divisione, connettori e anteprima 3D funzionano nel browser: niente da installare e il tuo modello non lascia mai il computer.", "Nee. Opsplitsen, verbindingen maken en het 3D-voorbeeld draaien in je browser — niets te installeren, en je model verlaat nooit je computer.", "Nie. Podział, tworzenie łączników i podgląd 3D działają w przeglądarce — nic nie trzeba instalować, a model nigdy nie opuszcza Twojego komputera.", "不要です。分割、コネクター生成、3Dプレビューはすべてブラウザで動作し、モデルがパソコンの外に出ることはありません。"],
    "How does pricing work?": ["Como funciona o preço?", "¿Cómo funcionan los precios?", "Wie funktionieren die Preise?", "Comment fonctionnent les tarifs ?", "Come funzionano i prezzi?", "Hoe werkt de prijs?", "Jak działa cennik?", "料金の仕組みは？"],
    "One plan at £3.99/month, cancel anytime — no tiers or feature gating. See the": ["Um único plano de £3,99/mês, cancele quando quiser — sem níveis nem recursos bloqueados. Veja as", "Un único plan de 3,99 £/mes, cancela cuando quieras: sin niveles ni funciones bloqueadas. Consulta las", "Ein Tarif für 3,99 £/Monat, jederzeit kündbar — keine Stufen, keine gesperrten Funktionen. Siehe die", "Une seule formule à 3,99 £/mois, annulable à tout moment — sans paliers ni fonctions bloquées. Voir la", "Un unico piano a 3,99 £/mese, disdici quando vuoi: nessun livello né funzioni bloccate. Vedi le", "Eén abonnement van £3,99/maand, altijd opzegbaar — geen niveaus of afgeschermde functies. Zie de", "Jeden plan za 3,99 £/mies., anuluj w każdej chwili — bez poziomów i blokad funkcji. Zobacz", "プランは月額£3.99のひとつだけ。いつでも解約でき、機能制限もありません。料金の詳細は"],
    "full FAQ": ["perguntas frequentes completas", "preguntas frecuentes completas", "vollständigen FAQ", "FAQ complète", "FAQ complete", "volledige FAQ", "pełne FAQ", "FAQ全文"],
    "for billing details.": ["para detalhes de cobrança.", "para ver los detalles de facturación.", "für Details zur Abrechnung.", "pour les détails de facturation.", "per i dettagli di fatturazione.", "voor factuurdetails.", "ze szczegółami płatności.", "をご覧ください。"],
    "Stop designing around your bed size.": ["Pare de projetar pensando no tamanho da mesa.", "Deja de diseñar pensando en el tamaño de tu cama.", "Hör auf, um dein Druckbett herum zu konstruieren.", "Arrêtez de concevoir en fonction de la taille de votre plateau.", "Smetti di progettare in base al piatto.", "Stop met ontwerpen rond je bedformaat.", "Przestań projektować pod wymiar stołu.", "ベッドサイズに合わせて設計するのはもうやめましょう。"],
    "Model at whatever scale the idea needs — PrintSlice figures out how to print it.": ["Modele na escala que a ideia pedir — o PrintSlice descobre como imprimir.", "Modela a la escala que necesite la idea: PrintSlice averigua cómo imprimirlo.", "Modelliere in der Größe, die die Idee braucht — PrintSlice findet heraus, wie es gedruckt wird.", "Modélisez à l'échelle que demande l'idée — PrintSlice trouve comment l'imprimer.", "Modella alla scala che serve all'idea: PrintSlice capisce come stamparla.", "Modelleer op de schaal die het idee nodig heeft — PrintSlice zoekt uit hoe het geprint wordt.", "Projektuj w takiej skali, jakiej wymaga pomysł — PrintSlice wymyśli, jak to wydrukować.", "アイデアに必要なスケールでモデリングを。印刷方法はPrintSliceが考えます。"],
    "PrintSlice splitting a 3D model and adding connectors": ["PrintSlice dividindo um modelo 3D e adicionando conectores", "PrintSlice dividiendo un modelo 3D y añadiendo conectores", "PrintSlice teilt ein 3D-Modell und fügt Verbinder hinzu", "PrintSlice découpe un modèle 3D et ajoute des connecteurs", "PrintSlice divide un modello 3D e aggiunge connettori", "PrintSlice splitst een 3D-model en voegt verbindingen toe", "PrintSlice dzieli model 3D i dodaje łączniki", "PrintSliceが3Dモデルを分割しコネクターを追加"],
    "PrintSlice viewport showing a loaded model split into pieces": ["Tela do PrintSlice com um modelo dividido em peças", "Visor de PrintSlice con un modelo dividido en piezas", "PrintSlice-Ansicht mit einem in Teile zerlegten Modell", "Vue PrintSlice montrant un modèle découpé en pièces", "Vista di PrintSlice con un modello diviso in pezzi", "PrintSlice-venster met een in stukken gesplitst model", "Widok PrintSlice z modelem podzielonym na części", "パーツに分割されたモデルを表示するPrintSliceの画面"],

    // free trial page
    "Free to try — no card": ["Teste grátis — sem cartão", "Pruébalo gratis, sin tarjeta", "Kostenlos testen — ohne Karte", "Essai gratuit — sans carte", "Prova gratis, senza carta", "Gratis te proberen — zonder kaart", "Za darmo — bez karty", "無料でお試し — カード不要"],
    "Print models bigger than your bed": ["Imprima modelos maiores que sua mesa", "Imprime modelos más grandes que tu cama", "Drucke Modelle, die größer sind als dein Druckbett", "Imprimez des modèles plus grands que votre plateau", "Stampa modelli più grandi del tuo piatto", "Print modellen die groter zijn dan je printbed", "Drukuj modele większe niż Twój stół", "ベッドより大きなモデルを印刷"],
    "Drop in an STL and PrintSlice cuts it into pieces that fit your printer — with snap-fit joints so they click back together.": ["Solte um STL e o PrintSlice corta em peças que cabem na sua impressora — com encaixes para montar de novo com um clique.", "Suelta un STL y PrintSlice lo corta en piezas que caben en tu impresora, con uniones a presión para volver a encajarlas.", "STL reinziehen, und PrintSlice schneidet es in Teile, die in deinen Drucker passen — mit Steckverbindungen, die wieder zusammenklicken.", "Déposez un STL et PrintSlice le découpe en pièces adaptées à votre imprimante — avec des assemblages qui s'emboîtent d'un clic.", "Trascina un STL e PrintSlice lo taglia in pezzi adatti alla tua stampante, con incastri che si richiudono con un clic.", "Zet een STL neer en PrintSlice snijdt hem in stukken die in je printer passen — met kliksluitingen zodat ze weer in elkaar passen.", "Upuść plik STL, a PrintSlice potnie go na części pasujące do Twojej drukarki — z zatrzaskami, które znów się złączą.", "STLをドロップすれば、PrintSliceがプリンターに収まるパーツに分割。はめ込み式なのでカチッと組み立てられます。"],
    "Try it free": ["Teste grátis", "Pruébalo gratis", "Kostenlos testen", "Essayer gratuitement", "Provalo gratis", "Gratis proberen", "Wypróbuj za darmo", "無料で試す"],
    "No card to sign up and split your models.": ["Sem cartão para criar conta e dividir seus modelos.", "Sin tarjeta para registrarte y dividir tus modelos.", "Keine Karte nötig, um dich anzumelden und Modelle aufzuteilen.", "Aucune carte pour vous inscrire et découper vos modèles.", "Nessuna carta per registrarti e dividere i tuoi modelli.", "Geen kaart nodig om je aan te melden en modellen te splitsen.", "Bez karty przy rejestracji i dzieleniu modeli.", "登録と分割にカードは不要です。"],
    "Load your STL": ["Carregue seu STL", "Carga tu STL", "STL laden", "Chargez votre STL", "Carica il tuo STL", "Laad je STL", "Wczytaj plik STL", "STLを読み込む"],
    "Or try our sample model if you don't have one handy.": ["Ou use nosso modelo de exemplo se não tiver um à mão.", "O prueba nuestro modelo de ejemplo si no tienes uno a mano.", "Oder nimm unser Beispielmodell, falls du keins zur Hand hast.", "Ou essayez notre modèle d'exemple si vous n'en avez pas sous la main.", "Oppure prova il nostro modello di esempio se non ne hai uno.", "Of probeer ons voorbeeldmodel als je er geen bij de hand hebt.", "Albo wypróbuj nasz przykładowy model, jeśli nie masz własnego.", "手元になければサンプルモデルでも試せます。"],
    "Enter your bed size": ["Informe o tamanho da mesa", "Indica el tamaño de tu cama", "Druckbettgröße eingeben", "Indiquez la taille du plateau", "Inserisci la misura del piatto", "Vul je bedformaat in", "Podaj wymiar stołu", "ベッドサイズを入力"],
    "The size of your printer's build plate, in mm.": ["O tamanho da mesa de impressão, em mm.", "El tamaño de la cama de tu impresora, en mm.", "Die Größe deiner Druckplatte in mm.", "La taille du plateau de votre imprimante, en mm.", "La misura del piatto della stampante, in mm.", "De grootte van de bouwplaat van je printer, in mm.", "Wymiar stołu Twojej drukarki w mm.", "プリンターの造形プレートのサイズ（mm）。"],
    "Split & download": ["Divida e baixe", "Divide y descarga", "Aufteilen & herunterladen", "Découpez et téléchargez", "Dividi e scarica", "Splitsen en downloaden", "Podziel i pobierz", "分割してダウンロード"],
    "Get print-ready pieces, joints included.": ["Receba peças prontas para imprimir, com encaixes.", "Obtén piezas listas para imprimir, con uniones incluidas.", "Druckfertige Teile, Verbinder inklusive.", "Obtenez des pièces prêtes à imprimer, assemblages compris.", "Ottieni pezzi pronti da stampare, incastri inclusi.", "Krijg printklare stukken, verbindingen inbegrepen.", "Gotowe do druku części, razem ze złączami.", "ジョイント付きの印刷用パーツが手に入ります。"],
    "Downloading your pieces needs a free 7-day trial: you'll add a card then, but you won't be charged until day 7, and you pay nothing if you cancel before. After that it's £3.99/month, cancel anytime.": ["Para baixar suas peças é preciso um teste grátis de 7 dias: você adiciona um cartão nesse momento, mas só é cobrado no 7º dia, e não paga nada se cancelar antes. Depois são £3,99/mês, cancele quando quiser.", "Para descargar tus piezas necesitas una prueba gratis de 7 días: añadirás una tarjeta en ese momento, pero no se te cobrará hasta el día 7 y no pagas nada si cancelas antes. Después son 3,99 £/mes, cancela cuando quieras.", "Zum Herunterladen brauchst du einen kostenlosen 7-Tage-Test: Dabei hinterlegst du eine Karte, belastet wird sie aber erst an Tag 7 — und gar nicht, wenn du vorher kündigst. Danach 3,99 £/Monat, jederzeit kündbar.", "Pour télécharger vos pièces, il faut un essai gratuit de 7 jours : vous ajoutez alors une carte, mais vous n'êtes débité qu'au 7e jour, et vous ne payez rien si vous annulez avant. Ensuite, c'est 3,99 £/mois, annulable à tout moment.", "Per scaricare i pezzi serve una prova gratuita di 7 giorni: aggiungi una carta in quel momento, ma l'addebito avviene solo al 7° giorno e non paghi nulla se disdici prima. Poi costa 3,99 £/mese, disdici quando vuoi.", "Om je stukken te downloaden heb je een gratis proefperiode van 7 dagen nodig: dan voeg je een kaart toe, maar je betaalt pas op dag 7, en niets als je eerder opzegt. Daarna £3,99/maand, altijd opzegbaar.", "Pobieranie części wymaga 7-dniowego okresu próbnego: wtedy dodajesz kartę, ale opłata pobierana jest dopiero 7. dnia, a jeśli anulujesz wcześniej, nic nie płacisz. Potem 3,99 £/mies., anuluj w każdej chwili.", "パーツのダウンロードには7日間の無料トライアルが必要です。その際にカードを登録しますが、請求は7日目からで、それまでに解約すれば料金はかかりません。その後は月額£3.99、いつでも解約できます。"],
    "← Back to PrintSlice": ["← Voltar ao PrintSlice", "← Volver a PrintSlice", "← Zurück zu PrintSlice", "← Retour à PrintSlice", "← Torna a PrintSlice", "← Terug naar PrintSlice", "← Wróć do PrintSlice", "← PrintSliceに戻る"],
    "PrintSlice splitting a 3D model into bed-sized pieces": ["PrintSlice dividindo um modelo 3D em peças do tamanho da mesa", "PrintSlice dividiendo un modelo 3D en piezas del tamaño de la cama", "PrintSlice teilt ein 3D-Modell in druckbettgroße Teile", "PrintSlice découpe un modèle 3D à la taille du plateau", "PrintSlice divide un modello 3D in pezzi a misura di piatto", "PrintSlice splitst een 3D-model in stukken op bedformaat", "PrintSlice dzieli model 3D na części na wymiar stołu", "PrintSliceが3Dモデルをベッドサイズに分割"],
    "Early Access — PrintSlice": ["Teste grátis — PrintSlice", "Prueba gratis — PrintSlice", "Kostenlos testen — PrintSlice", "Essai gratuit — PrintSlice", "Prova gratuita — PrintSlice", "Gratis proberen — PrintSlice", "Wypróbuj za darmo — PrintSlice", "無料トライアル — PrintSlice"],

    // app: sign-in
    "STL Bed Splitter": ["Divisor de STL", "Divisor de STL", "STL-Aufteiler", "Découpeur STL", "Divisore STL", "STL-splitter", "Dzielnik STL", "STL分割ツール"],
    "Loading…": ["Carregando…", "Cargando…", "Wird geladen…", "Chargement…", "Caricamento…", "Laden…", "Ładowanie…", "読み込み中…"],
    "Log in": ["Entrar", "Iniciar sesión", "Anmelden", "Se connecter", "Accedi", "Inloggen", "Zaloguj się", "ログイン"],
    "Welcome back — log in to your account.": ["Que bom te ver de novo — entre na sua conta.", "Hola de nuevo: inicia sesión en tu cuenta.", "Willkommen zurück — melde dich an.", "Bon retour — connectez-vous à votre compte.", "Bentornato: accedi al tuo account.", "Welkom terug — log in op je account.", "Witaj ponownie — zaloguj się na konto.", "おかえりなさい。アカウントにログインしてください。"],
    "Sign up": ["Criar conta", "Registrarse", "Registrieren", "S'inscrire", "Registrati", "Aanmelden", "Zarejestruj się", "新規登録"],
    "Try it free — no card needed to upload and split your model. You'll only add one when you're ready to download.": ["Teste grátis — sem cartão para enviar e dividir seu modelo. Você só adiciona um quando quiser baixar.", "Pruébalo gratis: sin tarjeta para subir y dividir tu modelo. Solo añadirás una cuando quieras descargar.", "Kostenlos testen — keine Karte nötig zum Hochladen und Aufteilen. Eine Karte brauchst du erst zum Herunterladen.", "Essai gratuit — aucune carte pour importer et découper votre modèle. Vous n'en ajouterez une que pour télécharger.", "Provalo gratis: nessuna carta per caricare e dividere il modello. La aggiungerai solo quando vorrai scaricare.", "Gratis proberen — geen kaart nodig om je model te uploaden en te splitsen. Die voeg je pas toe als je wilt downloaden.", "Za darmo — bez karty możesz wgrać i podzielić model. Kartę dodasz dopiero przy pobieraniu.", "無料でお試し。モデルのアップロードと分割にカードは不要で、ダウンロード時にだけ登録します。"],
    "Email": ["E-mail", "Correo electrónico", "E-Mail", "E-mail", "Email", "E-mail", "E-mail", "メールアドレス"],
    "Password": ["Senha", "Contraseña", "Passwort", "Mot de passe", "Password", "Wachtwoord", "Hasło", "パスワード"],
    "I'm 18 or over, and I agree to the": ["Tenho 18 anos ou mais e concordo com os", "Tengo 18 años o más y acepto los", "Ich bin mindestens 18 Jahre alt und akzeptiere die", "J'ai 18 ans ou plus et j'accepte les", "Ho almeno 18 anni e accetto i", "Ik ben 18 jaar of ouder en ga akkoord met de", "Mam co najmniej 18 lat i akceptuję", "18歳以上であり、"],
    "and": ["e a", "y la", "und die", "et la", "e", "en het", "oraz", "と"],
    "Privacy Policy": ["Política de Privacidade", "Política de privacidad", "Datenschutzerklärung", "Politique de confidentialité", "l'Informativa sulla privacy", "privacybeleid", "Politykę prywatności", "プライバシーポリシーに同意します"],
    "Don't have an account?": ["Não tem conta?", "¿No tienes cuenta?", "Noch kein Konto?", "Pas encore de compte ?", "Non hai un account?", "Nog geen account?", "Nie masz konta?", "アカウントをお持ちでないですか？"],
    "Already have an account?": ["Já tem conta?", "¿Ya tienes cuenta?", "Schon ein Konto?", "Déjà un compte ?", "Hai già un account?", "Heb je al een account?", "Masz już konto?", "アカウントをお持ちですか？"],
    "Enter an email and password.": ["Informe um e-mail e uma senha.", "Introduce un correo y una contraseña.", "Gib eine E-Mail-Adresse und ein Passwort ein.", "Saisissez un e-mail et un mot de passe.", "Inserisci email e password.", "Vul een e-mailadres en wachtwoord in.", "Podaj e-mail i hasło.", "メールアドレスとパスワードを入力してください。"],
    "Please confirm you're 18 or over and agree to the Terms to sign up.": ["Confirme que tem 18 anos ou mais e aceita os Termos para criar sua conta.", "Confirma que tienes 18 años o más y aceptas los Términos para registrarte.", "Bitte bestätige, dass du mindestens 18 bist und die AGB akzeptierst.", "Veuillez confirmer que vous avez 18 ans ou plus et acceptez les Conditions pour vous inscrire.", "Conferma di avere almeno 18 anni e di accettare i Termini per registrarti.", "Bevestig dat je 18 of ouder bent en akkoord gaat met de voorwaarden om je aan te melden.", "Potwierdź, że masz co najmniej 18 lat i akceptujesz Regulamin, aby się zarejestrować.", "登録するには、18歳以上であることと利用規約への同意を確認してください。"],

    // app: header and banners
    "Help & FAQ": ["Ajuda e dúvidas", "Ayuda y preguntas", "Hilfe & FAQ", "Aide & FAQ", "Aiuto e FAQ", "Help & FAQ", "Pomoc i FAQ", "ヘルプ・FAQ"],
    "Manage billing": ["Gerenciar cobrança", "Gestionar facturación", "Abrechnung verwalten", "Gérer la facturation", "Gestisci fatturazione", "Facturering beheren", "Zarządzaj płatnościami", "お支払い管理"],
    "Log out": ["Sair", "Cerrar sesión", "Abmelden", "Se déconnecter", "Esci", "Uitloggen", "Wyloguj się", "ログアウト"],
    "Known issue:": ["Problema conhecido:", "Problema conocido:", "Bekanntes Problem:", "Problème connu :", "Problema noto:", "Bekend probleem:", "Znany problem:", "既知の問題："],
    "extremely complex or very dense models can sometimes fail to place connectors or export correctly. We're actively working on this — see the": ["modelos muito complexos ou densos às vezes não conseguem receber conectores ou exportar corretamente. Estamos trabalhando nisso — veja a página de", "los modelos muy complejos o densos a veces no logran colocar conectores o exportarse correctamente. Estamos trabajando en ello; consulta la página de", "bei extrem komplexen oder sehr dichten Modellen können das Platzieren von Verbindern oder der Export manchmal fehlschlagen. Wir arbeiten daran — siehe", "avec des modèles extrêmement complexes ou très denses, le placement des connecteurs ou l'export peuvent parfois échouer. Nous y travaillons — consultez la page", "con modelli molto complessi o densi a volte i connettori o l'esportazione possono non riuscire. Ci stiamo lavorando: consulta la pagina", "bij extreem complexe of zeer dichte modellen kan het plaatsen van verbindingen of exporteren soms mislukken. We werken eraan — zie de pagina", "przy bardzo złożonych lub gęstych modelach dodawanie łączników lub eksport czasem się nie udaje. Pracujemy nad tym — zajrzyj na stronę", "非常に複雑・高密度なモデルでは、コネクターの配置や書き出しに失敗することがあります。現在対応中です。当面の回避方法は"],
    "page for workarounds in the meantime.": ["para soluções provisórias.", "para ver soluciones provisionales.", "für Workarounds in der Zwischenzeit.", "pour des solutions de contournement en attendant.", "per le soluzioni temporanee.", "voor tijdelijke oplossingen.", "z obejściami problemu.", "のページをご覧ください。"],
    "Dismiss": ["Dispensar", "Descartar", "Schließen", "Ignorer", "Chiudi", "Sluiten", "Zamknij", "閉じる"],
    "You're trying PrintSlice free.": ["Você está testando o PrintSlice grátis.", "Estás probando PrintSlice gratis.", "Du testest PrintSlice kostenlos.", "Vous essayez PrintSlice gratuitement.", "Stai provando PrintSlice gratis.", "Je probeert PrintSlice gratis.", "Testujesz PrintSlice za darmo.", "PrintSliceを無料でお試し中です。"],
    "Upload, split and add connectors as much as you like — you'll only need to start your free trial when you're ready to download.": ["Envie, divida e adicione conectores à vontade — você só precisa iniciar o teste grátis quando quiser baixar.", "Sube, divide y añade conectores todo lo que quieras: solo tendrás que empezar la prueba gratis cuando quieras descargar.", "Hochladen, aufteilen und Verbinder hinzufügen, so viel du willst — den kostenlosen Test brauchst du erst zum Herunterladen.", "Importez, découpez et ajoutez des connecteurs autant que vous voulez — vous n'aurez besoin de l'essai gratuit que pour télécharger.", "Carica, dividi e aggiungi connettori quanto vuoi: dovrai iniziare la prova gratuita solo quando vorrai scaricare.", "Upload, splits en voeg verbindingen toe zoveel je wilt — je start pas een gratis proefperiode als je wilt downloaden.", "Wgrywaj, dziel i dodawaj łączniki do woli — okres próbny zaczniesz dopiero, gdy zechcesz coś pobrać.", "アップロード、分割、コネクター追加はいくらでも可能です。無料トライアルはダウンロードするときだけ必要です。"],
    "Start free trial": ["Iniciar teste grátis", "Empezar prueba gratis", "Kostenlos testen", "Commencer l'essai gratuit", "Inizia la prova gratuita", "Start gratis proefperiode", "Zacznij okres próbny", "無料トライアルを開始"],
    "Your trial has ended.": ["Seu teste terminou.", "Tu prueba ha terminado.", "Dein Test ist abgelaufen.", "Votre essai est terminé.", "La tua prova è terminata.", "Je proefperiode is afgelopen.", "Twój okres próbny się skończył.", "トライアルは終了しました。"],
    "You can still upload, split and preview — subscribe to download your pieces again.": ["Você ainda pode enviar, dividir e visualizar — assine para baixar suas peças de novo.", "Aún puedes subir, dividir y previsualizar: suscríbete para volver a descargar tus piezas.", "Hochladen, Aufteilen und Vorschau gehen weiterhin — abonniere, um wieder herunterzuladen.", "Vous pouvez toujours importer, découper et prévisualiser — abonnez-vous pour télécharger à nouveau vos pièces.", "Puoi ancora caricare, dividere e vedere l'anteprima: abbonati per scaricare di nuovo i tuoi pezzi.", "Je kunt nog steeds uploaden, splitsen en bekijken — abonneer om je stukken weer te downloaden.", "Nadal możesz wgrywać, dzielić i podglądać — subskrybuj, by znów pobierać części.", "アップロード、分割、プレビューは引き続き可能です。再びダウンロードするには購読してください。"],
    "Subscribe — £3.99/month": ["Assinar — £3,99/mês", "Suscribirse — 3,99 £/mes", "Abonnieren — 3,99 £/Monat", "S'abonner — 3,99 £/mois", "Abbonati — 3,99 £/mese", "Abonneren — £3,99/maand", "Subskrybuj — 3,99 £/mies.", "購読する — 月額£3.99"],
    "You're all set — your trial has started.": ["Tudo certo — seu teste começou.", "Todo listo: tu prueba ha empezado.", "Alles erledigt — dein Test hat begonnen.", "C'est fait — votre essai a commencé.", "Tutto pronto: la tua prova è iniziata.", "Helemaal klaar — je proefperiode is gestart.", "Gotowe — Twój okres próbny się zaczął.", "準備完了。トライアルが始まりました。"],
    "If your model is open in another tab, you can download it there now.": ["Se seu modelo estiver aberto em outra aba, já pode baixá-lo lá.", "Si tienes el modelo abierto en otra pestaña, ya puedes descargarlo allí.", "Wenn dein Modell in einem anderen Tab offen ist, kannst du es jetzt dort herunterladen.", "Si votre modèle est ouvert dans un autre onglet, vous pouvez maintenant le télécharger là-bas.", "Se il modello è aperto in un'altra scheda, ora puoi scaricarlo lì.", "Als je model in een ander tabblad openstaat, kun je het daar nu downloaden.", "Jeśli model jest otwarty w innej karcie, możesz go tam teraz pobrać.", "別のタブでモデルを開いている場合は、そちらでダウンロードできます。"],

    // app: download prompt
    "Your pieces are ready": ["Suas peças estão prontas", "Tus piezas están listas", "Deine Teile sind fertig", "Vos pièces sont prêtes", "I tuoi pezzi sono pronti", "Je stukken zijn klaar", "Twoje części są gotowe", "パーツの準備ができました"],
    "Start your free 7-day trial to download them. You won't be charged today — it's £3.99/month after day 7, and if you cancel before then you pay nothing.": ["Inicie seu teste grátis de 7 dias para baixá-las. Nada é cobrado hoje — são £3,99/mês depois do 7º dia, e se cancelar antes não paga nada.", "Empieza tu prueba gratis de 7 días para descargarlas. Hoy no se te cobra nada: son 3,99 £/mes a partir del día 7 y, si cancelas antes, no pagas nada.", "Starte deinen kostenlosen 7-Tage-Test, um sie herunterzuladen. Heute wird nichts berechnet — ab Tag 7 kostet es 3,99 £/Monat, und wenn du vorher kündigst, zahlst du nichts.", "Commencez votre essai gratuit de 7 jours pour les télécharger. Rien n'est débité aujourd'hui — c'est 3,99 £/mois après le 7e jour, et si vous annulez avant, vous ne payez rien.", "Inizia la prova gratuita di 7 giorni per scaricarli. Oggi non paghi nulla: dal 7° giorno costa 3,99 £/mese e, se disdici prima, non paghi niente.", "Start je gratis proefperiode van 7 dagen om ze te downloaden. Vandaag betaal je niets — na dag 7 is het £3,99/maand, en als je eerder opzegt betaal je niets.", "Zacznij 7-dniowy okres próbny, aby je pobrać. Dziś nic nie płacisz — od 7. dnia to 3,99 £/mies., a jeśli anulujesz wcześniej, nie zapłacisz nic.", "ダウンロードするには7日間の無料トライアルを開始してください。本日の請求はありません。7日目以降は月額£3.99で、それまでに解約すれば料金はかかりません。"],
    "Subscribe to download them — £3.99/month, cancel anytime.": ["Assine para baixá-las — £3,99/mês, cancele quando quiser.", "Suscríbete para descargarlas: 3,99 £/mes, cancela cuando quieras.", "Abonniere, um sie herunterzuladen — 3,99 £/Monat, jederzeit kündbar.", "Abonnez-vous pour les télécharger — 3,99 £/mois, annulable à tout moment.", "Abbonati per scaricarli: 3,99 £/mese, disdici quando vuoi.", "Abonneer om ze te downloaden — £3,99/maand, altijd opzegbaar.", "Subskrybuj, aby je pobrać — 3,99 £/mies., anuluj w każdej chwili.", "ダウンロードするには購読してください。月額£3.99、いつでも解約可能です。"],
    "Not now": ["Agora não", "Ahora no", "Nicht jetzt", "Pas maintenant", "Non ora", "Niet nu", "Nie teraz", "今はしない"],
    "Checkout opens in a new tab, so your model stays right here.": ["O pagamento abre em uma nova aba, então seu modelo continua aqui.", "El pago se abre en una pestaña nueva, así tu modelo se queda aquí.", "Die Bezahlung öffnet sich in einem neuen Tab — dein Modell bleibt hier.", "Le paiement s'ouvre dans un nouvel onglet, votre modèle reste ici.", "Il pagamento si apre in una nuova scheda, così il tuo modello resta qui.", "Afrekenen opent in een nieuw tabblad, dus je model blijft hier staan.", "Płatność otworzy się w nowej karcie, więc model zostanie tutaj.", "決済は新しいタブで開くので、モデルはこのまま残ります。"],
    "Checkout opened in a new tab — your download unlocks here as soon as you finish.": ["O pagamento abriu em uma nova aba — o download é liberado aqui assim que você terminar.", "El pago se ha abierto en una pestaña nueva: la descarga se desbloquea aquí en cuanto termines.", "Die Bezahlung wurde in einem neuen Tab geöffnet — der Download wird hier freigeschaltet, sobald du fertig bist.", "Le paiement s'est ouvert dans un nouvel onglet — le téléchargement se débloque ici dès que vous avez terminé.", "Il pagamento si è aperto in una nuova scheda: il download si sblocca qui appena finisci.", "Afrekenen is geopend in een nieuw tabblad — je download wordt hier vrijgegeven zodra je klaar bent.", "Płatność otworzyła się w nowej karcie — pobieranie odblokuje się tutaj, gdy skończysz.", "決済を新しいタブで開きました。完了するとここでダウンロードできるようになります。"],

    // app: steps and sidebar
    "Progress": ["Progresso", "Progreso", "Fortschritt", "Progression", "Avanzamento", "Voortgang", "Postęp", "進行状況"],
    "Load": ["Carregar", "Cargar", "Laden", "Charger", "Carica", "Laden", "Wczytaj", "読込"],
    "Printer": ["Impressora", "Impresora", "Drucker", "Imprimante", "Stampante", "Printer", "Drukarka", "プリンター"],
    "Split": ["Dividir", "Dividir", "Aufteilen", "Découper", "Dividi", "Splitsen", "Podziel", "分割"],
    "Download": ["Baixar", "Descargar", "Download", "Télécharger", "Scarica", "Downloaden", "Pobierz", "ダウンロード"],
    "Start by loading an STL file — or try the sample model.": ["Comece carregando um arquivo STL — ou use o modelo de exemplo.", "Empieza cargando un archivo STL o prueba el modelo de ejemplo.", "Lade zuerst eine STL-Datei — oder probier das Beispielmodell.", "Commencez par charger un fichier STL — ou essayez le modèle d'exemple.", "Inizia caricando un file STL, oppure prova il modello di esempio.", "Begin met het laden van een STL-bestand — of probeer het voorbeeldmodel.", "Zacznij od wczytania pliku STL — albo wypróbuj model przykładowy.", "まずSTLファイルを読み込むか、サンプルモデルを試してください。"],
    "Check the bed size below matches your printer, then press Split.": ["Confira se o tamanho da mesa abaixo é o da sua impressora e clique em Dividir.", "Comprueba que el tamaño de la cama coincide con tu impresora y pulsa Dividir.", "Prüfe, ob die Druckbettgröße unten zu deinem Drucker passt, dann klicke auf Aufteilen.", "Vérifiez que la taille du plateau ci-dessous correspond à votre imprimante, puis cliquez sur Découper.", "Controlla che la misura del piatto qui sotto sia quella della tua stampante, poi premi Dividi.", "Controleer of het bedformaat hieronder bij je printer past en klik op Splitsen.", "Sprawdź, czy wymiar stołu poniżej pasuje do drukarki, i kliknij Podziel.", "下のベッドサイズがプリンターと合っているか確認し、「分割」を押してください。"],
    "Press \"Split into bed-sized pieces\" below.": ["Clique em \"Dividir em peças do tamanho da mesa\" abaixo.", "Pulsa \"Dividir en piezas del tamaño de la cama\" abajo.", "Klicke unten auf \"In druckbettgroße Teile aufteilen\".", "Cliquez sur \"Découper à la taille du plateau\" ci-dessous.", "Premi \"Dividi in pezzi a misura di piatto\" qui sotto.", "Klik hieronder op \"Splitsen in stukken op bedformaat\".", "Kliknij poniżej \"Podziel na części na wymiar stołu\".", "下の「ベッドサイズに分割」を押してください。"],
    "Done! Download your pieces below — or use a piece's \"Preview & Add Joining Point\" to add snap-fit connectors first.": ["Pronto! Baixe suas peças abaixo — ou use \"Ver e adicionar encaixe\" em uma peça para adicionar conectores antes.", "¡Listo! Descarga tus piezas abajo, o usa \"Ver y añadir unión\" en una pieza para añadir conectores antes.", "Fertig! Lade deine Teile unten herunter — oder füge zuerst über \"Vorschau & Verbinder hinzufügen\" Steckverbinder hinzu.", "Terminé ! Téléchargez vos pièces ci-dessous — ou utilisez \"Aperçu et ajout de jonction\" sur une pièce pour ajouter d'abord des connecteurs.", "Fatto! Scarica i pezzi qui sotto, oppure usa \"Anteprima e aggiungi unione\" su un pezzo per aggiungere prima i connettori.", "Klaar! Download je stukken hieronder — of gebruik eerst \"Bekijken & verbinding toevoegen\" bij een stuk om kliksluitingen toe te voegen.", "Gotowe! Pobierz części poniżej — albo najpierw dodaj łączniki przez \"Podgląd i dodaj łącznik\" przy części.", "完了！下からパーツをダウンロードできます。先にコネクターを付けるには、パーツの「プレビュー＆接合ポイント追加」を使ってください。"],
    "Done! It fits in one piece — download it below.": ["Pronto! Cabe em uma peça só — baixe abaixo.", "¡Listo! Cabe en una sola pieza: descárgala abajo.", "Fertig! Es passt in einem Stück — unten herunterladen.", "Terminé ! Ça rentre en une seule pièce — téléchargez-la ci-dessous.", "Fatto! Ci sta in un unico pezzo: scaricalo qui sotto.", "Klaar! Het past in één stuk — download het hieronder.", "Gotowe! Mieści się w jednym kawałku — pobierz poniżej.", "完了！1パーツで収まります。下からダウンロードしてください。"],
    "Model": ["Modelo", "Modelo", "Modell", "Modèle", "Modello", "Model", "Model", "モデル"],
    "Click to choose an STL file": ["Clique para escolher um arquivo STL", "Haz clic para elegir un archivo STL", "Klicken, um eine STL-Datei zu wählen", "Cliquez pour choisir un fichier STL", "Clicca per scegliere un file STL", "Klik om een STL-bestand te kiezen", "Kliknij, aby wybrać plik STL", "クリックしてSTLファイルを選択"],
    "or drag one here": ["ou arraste um até aqui", "o arrastra uno aquí", "oder hierher ziehen", "ou glissez-le ici", "o trascinalo qui", "of sleep er een hierheen", "lub przeciągnij go tutaj", "またはここにドラッグ"],
    "No file loaded.": ["Nenhum arquivo carregado.", "No hay ningún archivo cargado.", "Keine Datei geladen.", "Aucun fichier chargé.", "Nessun file caricato.", "Geen bestand geladen.", "Nie wczytano pliku.", "ファイルが読み込まれていません。"],
    "File:": ["Arquivo:", "Archivo:", "Datei:", "Fichier :", "File:", "Bestand:", "Plik:", "ファイル："],
    "Footprint fits bed:": ["Cabe na mesa (área):", "Cabe en la cama (superficie):", "Grundfläche passt aufs Bett:", "Emprise compatible avec le plateau :", "Ingombro adatto al piatto:", "Oppervlak past op bed:", "Podstawa mieści się na stole:", "底面がベッドに収まる："],
    "Height fits bed Z:": ["Altura cabe no Z:", "La altura cabe en Z:", "Höhe passt in Z:", "Hauteur compatible avec Z :", "Altezza adatta a Z:", "Hoogte past in Z:", "Wysokość mieści się w Z:", "高さがZに収まる："],
    "yes": ["sim", "sí", "ja", "oui", "sì", "ja", "tak", "はい"],
    "no — splitting needed": ["não — precisa dividir", "no: hay que dividir", "nein — Aufteilen nötig", "non — découpe nécessaire", "no: serve dividere", "nee — opsplitsen nodig", "nie — trzeba podzielić", "いいえ — 分割が必要"],
    "Target triangles": ["Triângulos desejados", "Triángulos objetivo", "Ziel-Dreiecke", "Triangles visés", "Triangoli obiettivo", "Doelaantal driehoeken", "Docelowa liczba trójkątów", "目標の三角形数"],
    "Preview simplified": ["Ver versão simplificada", "Ver versión simplificada", "Vereinfachte Vorschau", "Aperçu simplifié", "Anteprima semplificata", "Vereenvoudigd voorbeeld", "Podgląd uproszczony", "簡略化をプレビュー"],
    "Use this simplified version": ["Usar esta versão simplificada", "Usar esta versión simplificada", "Diese vereinfachte Version verwenden", "Utiliser cette version simplifiée", "Usa questa versione semplificata", "Deze vereenvoudigde versie gebruiken", "Użyj tej uproszczonej wersji", "この簡略版を使う"],
    "Keep original": ["Manter original", "Mantener original", "Original behalten", "Garder l'original", "Mantieni originale", "Origineel behouden", "Zachowaj oryginał", "元のまま使う"],
    "Printer bed size (mm)": ["Tamanho da mesa (mm)", "Tamaño de la cama (mm)", "Druckbettgröße (mm)", "Taille du plateau (mm)", "Misura del piatto (mm)", "Bedformaat (mm)", "Wymiar stołu (mm)", "ベッドサイズ (mm)"],
    "Bed X": ["Mesa X", "Cama X", "Bett X", "Plateau X", "Piatto X", "Bed X", "Stół X", "ベッド X"],
    "Bed Y": ["Mesa Y", "Cama Y", "Bett Y", "Plateau Y", "Piatto Y", "Bed Y", "Stół Y", "ベッド Y"],
    "Bed Z (max height)": ["Mesa Z (altura máx.)", "Cama Z (altura máx.)", "Bett Z (max. Höhe)", "Plateau Z (hauteur max.)", "Piatto Z (altezza max)", "Bed Z (max. hoogte)", "Stół Z (maks. wysokość)", "ベッド Z（最大高さ）"],
    "Safety margin per side (mm)": ["Margem de segurança por lado (mm)", "Margen de seguridad por lado (mm)", "Sicherheitsabstand pro Seite (mm)", "Marge de sécurité par côté (mm)", "Margine di sicurezza per lato (mm)", "Veiligheidsmarge per zijde (mm)", "Margines bezpieczeństwa na stronę (mm)", "片側の安全余白 (mm)"],
    "Split into bed-sized pieces": ["Dividir em peças do tamanho da mesa", "Dividir en piezas del tamaño de la cama", "In druckbettgroße Teile aufteilen", "Découper à la taille du plateau", "Dividi in pezzi a misura di piatto", "Splitsen in stukken op bedformaat", "Podziel na części na wymiar stołu", "ベッドサイズに分割"],
    "Result": ["Resultado", "Resultado", "Ergebnis", "Résultat", "Risultato", "Resultaat", "Wynik", "結果"],
    "Load a model to begin.": ["Carregue um modelo para começar.", "Carga un modelo para empezar.", "Lade ein Modell, um zu beginnen.", "Chargez un modèle pour commencer.", "Carica un modello per iniziare.", "Laad een model om te beginnen.", "Wczytaj model, aby zacząć.", "モデルを読み込んで開始してください。"],
    "Download all as ZIP": ["Baixar tudo em ZIP", "Descargar todo en ZIP", "Alles als ZIP herunterladen", "Tout télécharger en ZIP", "Scarica tutto in ZIP", "Alles downloaden als ZIP", "Pobierz wszystko jako ZIP", "すべてZIPでダウンロード"],
    "This model already fits the bed. You can still press Split (it will produce a single piece).": ["Este modelo já cabe na mesa. Você ainda pode clicar em Dividir (vai gerar uma peça só).", "Este modelo ya cabe en la cama. Aun así puedes pulsar Dividir (generará una sola pieza).", "Dieses Modell passt schon aufs Druckbett. Du kannst trotzdem auf Aufteilen klicken (es entsteht ein einzelnes Teil).", "Ce modèle tient déjà sur le plateau. Vous pouvez quand même cliquer sur Découper (cela donnera une seule pièce).", "Questo modello sta già nel piatto. Puoi comunque premere Dividi (otterrai un solo pezzo).", "Dit model past al op het bed. Je kunt toch op Splitsen klikken (dan krijg je één stuk).", "Ten model już mieści się na stole. Nadal możesz kliknąć Podziel (powstanie jedna część).", "このモデルはすでにベッドに収まります。「分割」を押すこともできます（1パーツになります）。"],
    "Press \"Split into bed-sized pieces\" to generate a grid of pieces that fit your bed.": ["Clique em \"Dividir em peças do tamanho da mesa\" para gerar peças que cabem na sua mesa.", "Pulsa \"Dividir en piezas del tamaño de la cama\" para generar piezas que quepan en tu cama.", "Klicke auf \"In druckbettgroße Teile aufteilen\", um Teile zu erzeugen, die auf dein Druckbett passen.", "Cliquez sur \"Découper à la taille du plateau\" pour générer des pièces qui tiennent sur votre plateau.", "Premi \"Dividi in pezzi a misura di piatto\" per creare pezzi che stanno nel tuo piatto.", "Klik op \"Splitsen in stukken op bedformaat\" om stukken te maken die op je bed passen.", "Kliknij \"Podziel na części na wymiar stołu\", aby utworzyć części mieszczące się na stole.", "「ベッドサイズに分割」を押すと、ベッドに収まるパーツが作成されます。"],
    "Splitting...": ["Dividindo...", "Dividiendo...", "Wird aufgeteilt...", "Découpe en cours...", "Divisione in corso...", "Bezig met splitsen...", "Dzielenie...", "分割中..."],
    "fits bed": ["cabe na mesa", "cabe en la cama", "passt aufs Bett", "tient sur le plateau", "sta nel piatto", "past op bed", "mieści się", "ベッドに収まる"],
    "too big": ["grande demais", "demasiado grande", "zu groß", "trop grand", "troppo grande", "te groot", "za duże", "大きすぎ"],
    "Joining points:": ["Pontos de encaixe:", "Puntos de unión:", "Verbindungspunkte:", "Points de jonction :", "Punti di unione:", "Verbindingspunten:", "Punkty łączenia:", "接合ポイント："],
    "none yet — click \"+ Add Joining Point\" to place one": ["nenhum ainda — use \"Ver e adicionar encaixe\" em uma peça para adicionar", "ninguno aún: usa \"Ver y añadir unión\" en una pieza para añadir uno", "noch keine — über \"Vorschau & Verbinder hinzufügen\" bei einem Teil hinzufügen", "aucun pour l'instant — utilisez \"Aperçu et ajout de jonction\" sur une pièce", "ancora nessuno: usa \"Anteprima e aggiungi unione\" su un pezzo", "nog geen — gebruik \"Bekijken & verbinding toevoegen\" bij een stuk", "jeszcze brak — użyj \"Podgląd i dodaj łącznik\" przy części", "まだありません。パーツの「プレビュー＆接合ポイント追加」から追加できます"],
    "Some pieces exceed the bed — check margin/bed size.": ["Algumas peças passam do tamanho da mesa — confira a margem e o tamanho da mesa.", "Algunas piezas superan la cama: revisa el margen y el tamaño de la cama.", "Einige Teile sind größer als das Druckbett — prüfe Abstand und Druckbettgröße.", "Certaines pièces dépassent le plateau — vérifiez la marge et la taille du plateau.", "Alcuni pezzi superano il piatto: controlla margine e misura del piatto.", "Sommige stukken zijn groter dan het bed — controleer marge en bedformaat.", "Niektóre części przekraczają stół — sprawdź margines i wymiar stołu.", "一部のパーツがベッドを超えています。余白とベッドサイズを確認してください。"],
    "All pieces fit the bed.": ["Todas as peças cabem na mesa.", "Todas las piezas caben en la cama.", "Alle Teile passen aufs Druckbett.", "Toutes les pièces tiennent sur le plateau.", "Tutti i pezzi stanno nel piatto.", "Alle stukken passen op het bed.", "Wszystkie części mieszczą się na stole.", "すべてのパーツがベッドに収まります。"],
    "Pieces keep the model's original coordinates so they line up if reassembled; reorient/lay flat as needed in your slicer.": ["As peças mantêm as coordenadas originais do modelo para se alinharem na montagem; reoriente ou deite-as no fatiador se precisar.", "Las piezas conservan las coordenadas originales del modelo para alinearse al montarlas; reoriéntalas o túmbalas en tu laminador si hace falta.", "Die Teile behalten die Originalkoordinaten des Modells, damit sie beim Zusammensetzen passen; drehe oder lege sie bei Bedarf im Slicer flach.", "Les pièces conservent les coordonnées d'origine du modèle pour s'aligner au réassemblage ; réorientez-les ou posez-les à plat dans votre trancheur si besoin.", "I pezzi mantengono le coordinate originali del modello per allinearsi in fase di montaggio; riorientali o appoggiali in piano nello slicer se serve.", "Stukken behouden de oorspronkelijke coördinaten van het model zodat ze bij het monteren uitlijnen; draai of leg ze zo nodig plat in je slicer.", "Części zachowują oryginalne współrzędne modelu, by pasowały po złożeniu; w slicerze obróć je lub połóż płasko, jeśli trzeba.", "パーツは元の座標を保持しているので組み立て時に揃います。必要に応じてスライサーで向きを変えたり平置きにしてください。"],
    "Preview & Add Joining Point": ["Ver e adicionar encaixe", "Ver y añadir unión", "Vorschau & Verbinder hinzufügen", "Aperçu et ajout de jonction", "Anteprima e aggiungi unione", "Bekijken & verbinding toevoegen", "Podgląd i dodaj łącznik", "プレビュー＆接合ポイント追加"],
    "Download STL": ["Baixar STL", "Descargar STL", "STL herunterladen", "Télécharger le STL", "Scarica STL", "STL downloaden", "Pobierz STL", "STLをダウンロード"],

    // app: empty viewport
    "Drop your STL file here": ["Solte seu arquivo STL aqui", "Suelta aquí tu archivo STL", "STL-Datei hier ablegen", "Déposez votre fichier STL ici", "Trascina qui il tuo file STL", "Zet je STL-bestand hier neer", "Upuść tutaj plik STL", "ここにSTLファイルをドロップ"],
    "or click anywhere in this box to choose one": ["ou clique em qualquer lugar desta área para escolher", "o haz clic en cualquier parte de este cuadro para elegir uno", "oder irgendwo in dieses Feld klicken, um eine zu wählen", "ou cliquez n'importe où dans ce cadre pour en choisir un", "oppure clicca in questo riquadro per sceglierne uno", "of klik ergens in dit vak om er een te kiezen", "lub kliknij w dowolnym miejscu tego pola, aby wybrać", "またはこの枠内をクリックして選択"],
    "No file handy?": ["Não tem um arquivo?", "¿No tienes un archivo?", "Keine Datei zur Hand?", "Pas de fichier sous la main ?", "Non hai un file?", "Geen bestand bij de hand?", "Nie masz pliku?", "ファイルがない場合は"],
    "Try a sample model": ["Testar um modelo de exemplo", "Probar un modelo de ejemplo", "Beispielmodell ausprobieren", "Essayer un modèle d'exemple", "Prova un modello di esempio", "Probeer een voorbeeldmodel", "Wypróbuj model przykładowy", "サンプルモデルを試す"],
    "Loading sample…": ["Carregando exemplo…", "Cargando ejemplo…", "Beispiel wird geladen…", "Chargement de l'exemple…", "Caricamento esempio…", "Voorbeeld laden…", "Wczytywanie przykładu…", "サンプルを読み込み中…"],
    "Choose an STL file": ["Escolher um arquivo STL", "Elegir un archivo STL", "STL-Datei wählen", "Choisir un fichier STL", "Scegli un file STL", "Kies een STL-bestand", "Wybierz plik STL", "STLファイルを選択"],

    // app: part preview / connectors
    "Part Preview": ["Prévia da peça", "Vista previa de la pieza", "Teilvorschau", "Aperçu de la pièce", "Anteprima del pezzo", "Voorbeeld van onderdeel", "Podgląd części", "パーツプレビュー"],
    "Close": ["Fechar", "Cerrar", "Schließen", "Fermer", "Chiudi", "Sluiten", "Zamknij", "閉じる"],
    "Rotate/pan/zoom to inspect the part. Click a marker to select it.": ["Gire, mova e dê zoom para inspecionar a peça. Clique num marcador para selecioná-lo.", "Gira, desplaza y amplía para revisar la pieza. Haz clic en un marcador para seleccionarlo.", "Drehen, verschieben und zoomen, um das Teil zu prüfen. Klicke auf eine Markierung, um sie auszuwählen.", "Faites pivoter, déplacez et zoomez pour inspecter la pièce. Cliquez sur un repère pour le sélectionner.", "Ruota, sposta e ingrandisci per esaminare il pezzo. Clicca un marcatore per selezionarlo.", "Draai, verschuif en zoom om het onderdeel te bekijken. Klik op een markering om die te selecteren.", "Obracaj, przesuwaj i przybliżaj, aby obejrzeć część. Kliknij znacznik, aby go wybrać.", "回転・移動・ズームでパーツを確認できます。マーカーをクリックすると選択できます。"],
    "One connector per face — place a second one on a different face for a stronger join.": ["Um conector por face — coloque outro em uma face diferente para uma junção mais forte.", "Un conector por cara: coloca otro en una cara distinta para una unión más firme.", "Ein Verbinder pro Fläche — setze einen zweiten auf eine andere Fläche für eine stärkere Verbindung.", "Un connecteur par face — placez-en un second sur une autre face pour un assemblage plus solide.", "Un connettore per faccia: mettine un altro su una faccia diversa per un'unione più solida.", "Eén verbinding per vlak — plaats een tweede op een ander vlak voor een sterkere verbinding.", "Jeden łącznik na ścianę — dodaj drugi na innej ścianie, by złącze było mocniejsze.", "1つの面にコネクターは1つ。より強固にするには別の面にもう1つ配置してください。"],
    "While placing, the shape on the model shows the connector's actual size and position. Its color is a live fit check:": ["Ao posicionar, a forma no modelo mostra o tamanho e a posição reais do conector. A cor indica o encaixe em tempo real:", "Al colocarlo, la forma sobre el modelo muestra el tamaño y la posición reales del conector. Su color indica en directo si encaja:", "Beim Platzieren zeigt die Form auf dem Modell die echte Größe und Position des Verbinders. Die Farbe ist ein Live-Passungscheck:", "Pendant le placement, la forme sur le modèle montre la taille et la position réelles du connecteur. Sa couleur indique l'ajustement en direct :", "Durante il posizionamento, la forma sul modello mostra dimensioni e posizione reali del connettore. Il colore indica l'adattamento in tempo reale:", "Tijdens het plaatsen toont de vorm op het model de echte grootte en positie van de verbinding. De kleur is een live pascontrole:", "Podczas umieszczania kształt na modelu pokazuje rzeczywisty rozmiar i położenie łącznika. Kolor na bieżąco ocenia dopasowanie:", "配置中はモデル上の形状がコネクターの実際のサイズと位置を示し、色でリアルタイムに適合度を確認できます："],
    "green": ["verde", "verde", "grün", "vert", "verde", "groen", "zielony", "緑"],
    "= flat, reliable spot,": ["= plano, local confiável,", "= zona plana y fiable,", "= flach, zuverlässige Stelle,", "= plat, emplacement fiable,", "= piatto, punto affidabile,", "= vlak, betrouwbare plek,", "= płasko, pewne miejsce,", "＝平らで確実な位置、"],
    "yellow": ["amarelo", "amarillo", "gelb", "jaune", "giallo", "geel", "żółty", "黄"],
    "= some curve nearby,": ["= alguma curva por perto,", "= alguna curva cerca,", "= etwas Wölbung in der Nähe,", "= légère courbe à proximité,", "= qualche curva vicina,", "= wat kromming in de buurt,", "= w pobliżu jest krzywizna,", "＝近くに曲面あり、"],
    "red": ["vermelho", "rojo", "rot", "rouge", "rosso", "rood", "czerwony", "赤"],
    "= risky — try a flatter spot nearby.": ["= arriscado — tente um ponto mais plano por perto.", "= arriesgado: prueba una zona más plana cerca.", "= riskant — versuch eine flachere Stelle in der Nähe.", "= risqué — essayez un endroit plus plat à proximité.", "= rischioso: prova un punto più piatto vicino.", "= riskant — probeer een vlakkere plek in de buurt.", "= ryzykowne — spróbuj płaskiego miejsca obok.", "＝要注意。近くの平らな位置を試してください。"],
    "+ Add Joining Point": ["+ Adicionar ponto de encaixe", "+ Añadir punto de unión", "+ Verbindungspunkt hinzufügen", "+ Ajouter un point de jonction", "+ Aggiungi punto di unione", "+ Verbindingspunt toevoegen", "+ Dodaj punkt łączenia", "+ 接合ポイントを追加"],
    "Connector type": ["Tipo de conector", "Tipo de conector", "Verbindertyp", "Type de connecteur", "Tipo di connettore", "Type verbinding", "Typ łącznika", "コネクターの種類"],
    "Rectangular key": ["Chaveta retangular", "Chaveta rectangular", "Rechteckige Passfeder", "Clavette rectangulaire", "Chiavetta rettangolare", "Rechthoekige spie", "Klin prostokątny", "角キー"],
    "Pin & socket": ["Pino e soquete", "Pasador y hueco", "Stift & Buchse", "Goupille et logement", "Perno e foro", "Pen en gat", "Kołek i gniazdo", "ピン＆ソケット"],
    "Dovetail (locking)": ["Rabo de andorinha (trava)", "Cola de milano (bloqueo)", "Schwalbenschwanz (verriegelnd)", "Queue d'aronde (verrouillage)", "Coda di rondine (bloccante)", "Zwaluwstaart (vergrendelend)", "Jaskółczy ogon (blokujący)", "アリ継ぎ（ロック式）"],
    "Size (mm)": ["Tamanho (mm)", "Tamaño (mm)", "Größe (mm)", "Taille (mm)", "Dimensione (mm)", "Grootte (mm)", "Rozmiar (mm)", "サイズ (mm)"],
    "Depth (mm)": ["Profundidade (mm)", "Profundidad (mm)", "Tiefe (mm)", "Profondeur (mm)", "Profondità (mm)", "Diepte (mm)", "Głębokość (mm)", "深さ (mm)"],
    "Clearance (mm)": ["Folga (mm)", "Holgura (mm)", "Spiel (mm)", "Jeu (mm)", "Gioco (mm)", "Speling (mm)", "Luz (mm)", "クリアランス (mm)"],
    "Click anywhere on the part's surface below to place this connector — the matching male/female piece is created automatically on whichever part it connects to (pick a different one from the \"Connect to\" dropdown after placing if the guess is wrong).": ["Clique em qualquer ponto da superfície da peça abaixo para posicionar este conector — a parte macho/fêmea correspondente é criada automaticamente na peça a que ele se liga (se o palpite estiver errado, escolha outra no menu \"Connect to\" depois de posicionar).", "Haz clic en cualquier punto de la superficie de la pieza para colocar este conector: la pieza macho/hembra correspondiente se crea automáticamente en la pieza a la que se une (si no acierta, elige otra en el menú \"Connect to\" después de colocarlo).", "Klicke irgendwo auf die Oberfläche des Teils unten, um diesen Verbinder zu platzieren — das passende Gegenstück wird automatisch am angrenzenden Teil erzeugt (wähle nach dem Platzieren im Menü \"Connect to\" ein anderes, falls es falsch geraten ist).", "Cliquez n'importe où sur la surface de la pièce ci-dessous pour placer ce connecteur — la partie mâle/femelle correspondante est créée automatiquement sur la pièce à laquelle il se raccorde (choisissez-en une autre dans le menu \"Connect to\" après le placement si ce n'est pas la bonne).", "Clicca in un punto qualsiasi della superficie del pezzo qui sotto per posizionare il connettore: la parte maschio/femmina corrispondente viene creata automaticamente sul pezzo a cui si collega (se è sbagliato, scegline un altro dal menu \"Connect to\" dopo averlo posizionato).", "Klik ergens op het oppervlak van het onderdeel hieronder om deze verbinding te plaatsen — het bijpassende mannelijke/vrouwelijke deel wordt automatisch gemaakt op het onderdeel waarmee het verbindt (kies na het plaatsen een ander in het menu \"Connect to\" als de gok niet klopt).", "Kliknij w dowolnym miejscu powierzchni części poniżej, aby umieścić łącznik — pasujący element męski/żeński powstanie automatycznie na części, z którą się łączy (jeśli to nie ta, wybierz inną z listy \"Connect to\" po umieszczeniu).", "下のパーツ表面の任意の場所をクリックするとコネクターを配置できます。対応するオス/メス側は接続先のパーツに自動で作成されます（違う場合は配置後に「Connect to」メニューから変更してください）。"],
    "Delete": ["Excluir", "Eliminar", "Löschen", "Supprimer", "Elimina", "Verwijderen", "Usuń", "削除"],
    "Confirm delete?": ["Confirmar exclusão?", "¿Confirmar?", "Wirklich löschen?", "Confirmer la suppression ?", "Confermi?", "Verwijderen bevestigen?", "Potwierdzić usunięcie?", "削除しますか？"],
    "Move": ["Mover", "Mover", "Verschieben", "Déplacer", "Sposta", "Verplaatsen", "Przesuń", "移動"],

    // cookie banner (consent.js)
    "We'd like to use analytics cookies (Microsoft Clarity) to see how people use PrintSlice, so we can fix what's confusing. Anything you type is hidden.": ["Gostaríamos de usar cookies de análise (Microsoft Clarity) para ver como as pessoas usam o PrintSlice e corrigir o que for confuso. Tudo o que você digita fica oculto.", "Nos gustaría usar cookies de análisis (Microsoft Clarity) para ver cómo se usa PrintSlice y arreglar lo que resulte confuso. Todo lo que escribes queda oculto.", "Wir würden gern Analyse-Cookies (Microsoft Clarity) nutzen, um zu sehen, wie PrintSlice verwendet wird, damit wir Unklarheiten beheben können. Alles, was du eintippst, bleibt verborgen.", "Nous aimerions utiliser des cookies d'analyse (Microsoft Clarity) pour voir comment PrintSlice est utilisé et corriger ce qui prête à confusion. Tout ce que vous saisissez est masqué.", "Vorremmo usare cookie di analisi (Microsoft Clarity) per capire come viene usato PrintSlice e correggere ciò che confonde. Tutto ciò che scrivi resta nascosto.", "We willen graag analysecookies (Microsoft Clarity) gebruiken om te zien hoe mensen PrintSlice gebruiken, zodat we verwarrende dingen kunnen verbeteren. Alles wat je typt blijft verborgen.", "Chcielibyśmy używać analitycznych plików cookie (Microsoft Clarity), aby zobaczyć, jak ludzie korzystają z PrintSlice, i poprawić to, co jest niejasne. Wszystko, co wpisujesz, jest ukryte.", "PrintSliceの使われ方を把握して分かりにくい点を改善するため、分析用Cookie（Microsoft Clarity）を使用したいと考えています。入力内容は非表示になります。"],
    "Privacy policy": ["Política de Privacidade", "Política de privacidad", "Datenschutzerklärung", "Politique de confidentialité", "Informativa sulla privacy", "Privacybeleid", "Polityka prywatności", "プライバシーポリシー"],
    "Accept": ["Aceitar", "Aceptar", "Akzeptieren", "Accepter", "Accetta", "Accepteren", "Akceptuję", "同意する"],
    "Decline": ["Recusar", "Rechazar", "Ablehnen", "Refuser", "Rifiuta", "Weigeren", "Odrzucam", "拒否する"],

    // legal-page note (shown on terms/privacy for non-English visitors)
    "This page is only available in English.": ["Esta página está disponível apenas em inglês.", "Esta página solo está disponible en inglés.", "Diese Seite ist nur auf Englisch verfügbar.", "Cette page n'est disponible qu'en anglais.", "Questa pagina è disponibile solo in inglese.", "Deze pagina is alleen in het Engels beschikbaar.", "Ta strona jest dostępna tylko po angielsku.", "このページは英語のみでご覧いただけます。"]
  };

  // Text that contains numbers or file names — matched by pattern instead.
  var P = [
    [/^Triangles: (.+)$/, ["Triângulos: $1", "Triángulos: $1", "Dreiecke: $1", "Triangles : $1", "Triangoli: $1", "Driehoeken: $1", "Trójkąty: $1", "三角形数：$1"]],
    [/^Size \(X x Y x Z\): (.+)$/, ["Tamanho (X x Y x Z): $1", "Tamaño (X x Y x Z): $1", "Größe (X x Y x Z): $1", "Taille (X x Y x Z) : $1", "Dimensioni (X x Y x Z): $1", "Grootte (X x Y x Z): $1", "Rozmiar (X x Y x Z): $1", "サイズ (X×Y×Z)：$1"]],
    [/^Size: (.+)$/, ["Tamanho: $1", "Tamaño: $1", "Größe: $1", "Taille : $1", "Dimensioni: $1", "Grootte: $1", "Rozmiar: $1", "サイズ：$1"]],
    [/^Grid: (.+) = (\d+) piece\(s\)$/, ["Grade: $1 = $2 peça(s)", "Cuadrícula: $1 = $2 pieza(s)", "Raster: $1 = $2 Teil(e)", "Grille : $1 = $2 pièce(s)", "Griglia: $1 = $2 pezzo/i", "Raster: $1 = $2 stuk(ken)", "Siatka: $1 = $2 części", "グリッド：$1 = $2パーツ"]],
    [/^Volume check: (.+)% of original volume recovered$/, ["Verificação de volume: $1% do volume original recuperado", "Comprobación de volumen: $1 % del volumen original recuperado", "Volumenprüfung: $1 % des Originalvolumens erhalten", "Vérification du volume : $1 % du volume d'origine conservé", "Controllo volume: $1% del volume originale recuperato", "Volumecontrole: $1% van het oorspronkelijke volume behouden", "Kontrola objętości: odzyskano $1% oryginalnej objętości", "体積チェック：元の体積の$1%を維持"]],
    [/^(\d+) placed$/, ["$1 colocado(s)", "$1 colocado(s)", "$1 gesetzt", "$1 placé(s)", "$1 posizionato/i", "$1 geplaatst", "$1 dodano", "$1個配置済み"]],
    [/^Part (\d+) Preview$/, ["Prévia da peça $1", "Vista previa de la pieza $1", "Vorschau Teil $1", "Aperçu de la pièce $1", "Anteprima pezzo $1", "Voorbeeld onderdeel $1", "Podgląd części $1", "パーツ$1のプレビュー"]],
    [/^Part (\d+)( — .+)?$/, ["Peça $1$2", "Pieza $1$2", "Teil $1$2", "Pièce $1$2", "Pezzo $1$2", "Onderdeel $1$2", "Część $1$2", "パーツ$1$2"]]
  ];

  var idx = LANGS.indexOf(lang);
  var DN = {};
  for (var k in D) DN[norm(k)] = D[k];

  function translate(s){
    var key = norm(s);
    var hit = DN[key];
    if (hit) return hit[idx];
    for (var i = 0; i < P.length; i++){
      if (P[i][0].test(key)) return key.replace(P[i][0], P[i][1][idx]);
    }
    return null;
  }

  var SKIP_TAGS = { SCRIPT: 1, STYLE: 1, TEXTAREA: 1, CODE: 1, PRE: 1, NOSCRIPT: 1 };
  function skippable(el){
    for (var e = el; e && e.nodeType === 1; e = e.parentNode){
      if (SKIP_TAGS[e.tagName]) return true;
      if (e.classList && e.classList.contains("notranslate")) return true;
      if (e.getAttribute && e.getAttribute("translate") === "no") return true;
    }
    return false;
  }

  function trText(node){
    var v = node.nodeValue;
    if (!v || !/[A-Za-z]/.test(v)) return;
    var p = node.parentNode;
    if (!p || skippable(p)) return;
    var t = translate(v);
    if (t == null || t === norm(v)) return;
    node.nodeValue = v.match(/^\s*/)[0] + t + v.match(/\s*$/)[0];
  }

  var ATTRS = ["placeholder", "aria-label", "alt", "title"];
  function trAttrs(el){
    if (skippable(el)) return;
    for (var i = 0; i < ATTRS.length; i++){
      var v = el.getAttribute(ATTRS[i]);
      if (!v || !/[A-Za-z]/.test(v)) continue;
      var t = translate(v);
      if (t != null && t !== norm(v)) el.setAttribute(ATTRS[i], t);
    }
  }

  function trTree(root){
    if (root.nodeType === 3){ trText(root); return; }
    if (root.nodeType !== 1) return;
    trAttrs(root);
    var w = document.createTreeWalker(root, NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_TEXT, null);
    var n;
    while ((n = w.nextNode())){
      if (n.nodeType === 3) trText(n); else trAttrs(n);
    }
  }

  function runManual(){
    document.documentElement.lang = lang;
    // Watch from the very start so text is swapped as the parser inserts it —
    // no flash of English — and keeps catching anything the app writes later.
    new MutationObserver(function(muts){
      for (var i = 0; i < muts.length; i++){
        var m = muts[i];
        if (m.type === "characterData") trText(m.target);
        else if (m.type === "attributes") trAttrs(m.target);
        else for (var j = 0; j < m.addedNodes.length; j++) trTree(m.addedNodes[j]);
      }
    }).observe(document.documentElement, { childList: true, subtree: true, characterData: true, attributes: true, attributeFilter: ATTRS });
    trTree(document.documentElement);
    document.addEventListener("DOMContentLoaded", function(){ trTree(document.documentElement); });
  }

  function runGoogle(code){
    setGoogleCookie(code);
    var css = document.createElement("style");
    css.textContent =
      ".goog-te-banner-frame, iframe.goog-te-banner-frame, body > .skiptranslate, #goog-gt-tt, .goog-te-balloon-frame, " +
      ".VIpgJd-ZVi9od-ORHb-OEVmcd, .VIpgJd-ZVi9od-aZ2wEe-wOHMyf, .VIpgJd-yAWNEb-L7lbkb { display:none !important; }" +
      "body { top:0 !important; }" +
      ".goog-text-highlight { background:none !important; box-shadow:none !important; }";
    document.head.appendChild(css);
    window.__psGoogleInit = function(){
      new google.translate.TranslateElement({ pageLanguage: "en", autoDisplay: false }, "ps_gt");
    };
    document.addEventListener("DOMContentLoaded", function(){
      var holder = document.createElement("div");
      holder.id = "ps_gt"; holder.style.display = "none";
      document.body.appendChild(holder);
      var s = document.createElement("script");
      s.src = "https://translate.google.com/translate_a/element.js?cb=__psGoogleInit";
      document.body.appendChild(s);
    });
  }

  function englishOnlyNote(){
    document.addEventListener("DOMContentLoaded", function(){
      var bar = document.createElement("div");
      bar.className = "notranslate";
      bar.style.cssText = "background:#fff8e8;border-bottom:1px solid #e8c874;color:#6b4d06;font:13px/1.5 -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Arial,sans-serif;padding:9px 16px;text-align:center;";
      bar.textContent = idx >= 0 ? D["This page is only available in English."][idx] : "This page is only available in English.";
      document.body.insertBefore(bar, document.body.firstChild);
      if (idx < 0) return;
      // The legal text stays English, but the cookie banner (added to <body>
      // by consent.js) is still translated so people know what they're agreeing to.
      var isBanner = function(n){ return n.nodeType === 1 && n.getAttribute("role") === "dialog"; };
      Array.prototype.forEach.call(document.body.children, function(n){ if (isBanner(n)) trTree(n); });
      new MutationObserver(function(muts){
        muts.forEach(function(m){ Array.prototype.forEach.call(m.addedNodes, function(n){ if (isBanner(n)) trTree(n); }); });
      }).observe(document.body, { childList: true });
    });
  }

  function switcher(){
    document.addEventListener("DOMContentLoaded", function(){
      var wrap = document.createElement("div");
      wrap.className = "notranslate";
      wrap.setAttribute("translate", "no");
      wrap.style.cssText = "position:fixed;right:12px;bottom:12px;z-index:9000;";
      var sel = document.createElement("select");
      sel.setAttribute("aria-label", "Language");
      sel.style.cssText = "font:600 12.5px -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Arial,sans-serif;padding:6px 8px;border-radius:6px;" +
        "border:1px solid rgba(1,22,30,.25);background:#f8fbf0;color:#01161e;box-shadow:0 6px 18px -8px rgba(1,22,30,.35);cursor:pointer;width:auto;margin:0;";
      var codes = ["en"].concat(LANGS);
      // Also offer the current language and the browser's own one when they're
      // Google-translated ones, so someone who picks English can switch back.
      [lang, browserTag().split("-")[0]].forEach(function(c){
        if (codes.indexOf(c) >= 0) return;
        var name = c;
        try { name = new Intl.DisplayNames([c], { type: "language" }).of(c) || c; } catch (e) {}
        codes.push(c);
        NAMES[c] = name + " (Google)";
      });
      codes.forEach(function(c){
        var o = document.createElement("option");
        o.value = c; o.textContent = "🌐 " + NAMES[c];
        if (c === lang) o.selected = true;
        sel.appendChild(o);
      });
      sel.addEventListener("change", function(){
        try { localStorage.setItem(STORE, sel.value); } catch (e) {}
        clearGoogleCookie();
        location.reload();
      });
      wrap.appendChild(sel);
      document.body.appendChild(wrap);
    });
  }

  window.printsliceLang = lang;
  switcher();

  if (lang === "en"){ clearGoogleCookie(); return; }
  if (mode === "none"){ clearGoogleCookie(); englishOnlyNote(); return; }
  if (mode === "manual" && idx >= 0){ clearGoogleCookie(); runManual(); return; }
  runGoogle(googleCode(tag));
})();
